from __future__ import annotations

import csv
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
HISTORY_PATH = ROOT / "paper/tables/cea_server_status_history.csv"
REPORT_PATH = ROOT / "paper/cea_server_progress_report.md"


@dataclass
class RunProgress:
    run: str
    status: str
    first_epochs: int
    latest_epochs: int
    completion_gate: int
    first_timestamp: str
    latest_timestamp: str
    history_records: int
    recent_epoch_gain: int
    latest_map50: str
    latest_map50_95: str
    train_process: str
    queue_process: str

    @property
    def gained_epochs(self) -> int:
        return self.latest_epochs - self.first_epochs

    @property
    def completion_ratio(self) -> float:
        if self.completion_gate <= 0:
            return 0.0
        return min(self.latest_epochs / self.completion_gate, 1.0)


def to_int(value: str) -> int:
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return 0


def read_history() -> list[dict[str, str]]:
    if not HISTORY_PATH.exists():
        return []
    with HISTORY_PATH.open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def summarize(rows: list[dict[str, str]]) -> list[RunProgress]:
    grouped: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        grouped[row.get("run", "unknown")].append(row)

    progress: list[RunProgress] = []
    for run, items in grouped.items():
        first = items[0]
        latest = items[-1]
        previous = items[-2] if len(items) >= 2 else first
        progress.append(
            RunProgress(
                run=run,
                status=latest.get("status", ""),
                first_epochs=to_int(first.get("epochs", "")),
                latest_epochs=to_int(latest.get("epochs", "")),
                completion_gate=to_int(latest.get("completion_gate_epochs", "")),
                first_timestamp=first.get("timestamp", ""),
                latest_timestamp=latest.get("timestamp", ""),
                history_records=len(items),
                recent_epoch_gain=to_int(latest.get("epochs", "")) - to_int(previous.get("epochs", "")),
                latest_map50=latest.get("last_map50", ""),
                latest_map50_95=latest.get("last_map50_95", ""),
                train_process=latest.get("train_process", ""),
                queue_process=latest.get("queue_process", ""),
            )
        )
    return progress


def status_rank(item: RunProgress) -> tuple[int, str]:
    order = {"READY": 0, "PARTIAL": 1, "MISSING": 2}
    return (order.get(item.status, 3), item.run)


def write_report(progress: list[RunProgress]) -> None:
    total = len(progress)
    ready = sum(1 for item in progress if item.status == "READY")
    partial = sum(1 for item in progress if item.status == "PARTIAL")
    missing = sum(1 for item in progress if item.status == "MISSING")
    latest_timestamp = max((item.latest_timestamp for item in progress), default="")

    lines = [
        "# CEA Server Progress Report",
        "",
        "This report is generated by `tools/build_cea_server_progress_report.py` from `paper/tables/cea_server_status_history.csv`. It summarizes server-side fair-comparison progress without copying partial results into paper tables.",
        "",
        "## Summary",
        "",
        f"- Tracked runs: {total}",
        f"- Ready: {ready}",
        f"- Partial: {partial}",
        f"- Missing: {missing}",
        f"- Latest status timestamp: {latest_timestamp or 'n/a'}",
        "",
        "## Run Progress",
        "",
        "| Run | Status | Epochs | Completion | History Records | Total Epoch Gain | Recent Epoch Gain | Latest mAP50 | Latest mAP50-95 | First Seen | Latest Seen |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- | --- |",
    ]
    for item in sorted(progress, key=status_rank):
        completion = f"{item.completion_ratio * 100:.1f}%"
        lines.append(
            f"| {item.run} | {item.status} | {item.latest_epochs}/{item.completion_gate} | {completion} | {item.history_records} | {item.gained_epochs} | {item.recent_epoch_gain} | {item.latest_map50} | {item.latest_map50_95} | {item.first_timestamp} | {item.latest_timestamp} |"
        )

    lines.extend(
        [
            "",
            "## Latest Processes",
            "",
            "| Process | State |",
            "| --- | --- |",
        ]
    )
    latest_item = max(progress, key=lambda item: item.latest_timestamp, default=None)
    if latest_item:
        lines.append(f"| train | `{latest_item.train_process}` |")
        lines.append(f"| queue | `{latest_item.queue_process}` |")
    else:
        lines.append("| train | `n/a` |")
        lines.append("| queue | `n/a` |")

    lines.extend(
        [
            "",
            "## Evidence Rule",
            "",
            "This report is progress monitoring only. A run can enter paper-facing result tables only after the guarded sync protocol confirms a complete run with at least 100 epochs, `args.yaml`, `weights/best.pt`, logs, regenerated tables, and refreshed audits.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    rows = read_history()
    progress = summarize(rows)
    write_report(progress)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
