from __future__ import annotations

import csv
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "paper/advisor_progress_brief.md"


@dataclass
class RunSummary:
    model: str
    role: str
    imgsz: str
    best_map50: float
    best_map50_95: float
    run_dir: str


def read_csv_rows(rel_path: str) -> list[dict[str, str]]:
    path = ROOT / rel_path
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def to_float(value: str) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def percent(value: float) -> str:
    return f"{value * 100:.2f}%"


def points(value: float) -> str:
    return f"{value * 100:.2f} 个百分点"


def find_row(rows: list[dict[str, str]], model: str) -> dict[str, str]:
    for row in rows:
        if row.get("model") == model:
            return row
    return {}


def completed_runs(rows: list[dict[str, str]]) -> list[RunSummary]:
    runs: list[RunSummary] = []
    for row in rows:
        if row.get("status") != "completed":
            continue
        runs.append(
            RunSummary(
                model=row.get("model", ""),
                role=row.get("paper_role", ""),
                imgsz=row.get("imgsz", ""),
                best_map50=to_float(row.get("best_map50", "")),
                best_map50_95=to_float(row.get("best_map50_95", "")),
                run_dir=row.get("run_dir", ""),
            )
        )
    return runs


def read_server_snapshot() -> tuple[str, str, str]:
    path = ROOT / "paper/cea_server_status_snapshot.md"
    if not path.exists():
        return "未生成", "n/a", "n/a"
    text = path.read_text(encoding="utf-8")
    generated = re.search(r"Generated by .* at (.+)\.", text)
    row = re.search(r"\| baseline_yolo11n_960_visdrone \| ([A-Z]+) \| ([0-9]+) \|", text)
    process = re.search(r"\| train \| `([^`]+)` \|", text)
    status = "未找到 YOLO11n-960 状态"
    if row:
        status = f"{row.group(1)}，{row.group(2)}/100 epoch"
    return (
        generated.group(1) if generated else "n/a",
        status,
        process.group(1).strip() if process else "n/a",
    )


def scale_ratio(split: str, scale: str) -> str:
    for row in read_csv_rows("paper/tables/object_scale_distribution.csv"):
        if row.get("split") == split and row.get("scale") == scale:
            return percent(to_float(row.get("ratio", "")))
    return "n/a"


def scale_recall(model: str, scale: str) -> str:
    for row in read_csv_rows("paper/tables/scale_group_results.csv"):
        if row.get("model") == model and row.get("scale") == scale:
            return f"{to_float(row.get('recall', '')):.6f}"
    return "n/a"


def dashboard_summary() -> tuple[str, str, str, str, str]:
    path = ROOT / "paper/submission_audit_dashboard.md"
    if not path.exists():
        return ("n/a", "n/a", "n/a", "n/a", "n/a")
    text = path.read_text(encoding="utf-8")
    def get(label: str) -> str:
        match = re.search(rf"- {re.escape(label)}:\s*([0-9]+)", text)
        return match.group(1) if match else "n/a"
    return (
        get("Total audit reports"),
        get("Ready reports"),
        get("Partial reports"),
        get("Pending reports"),
        get("Missing reports"),
    )


def build_brief() -> str:
    rows = read_csv_rows("paper/tables/main_results.csv")
    runs = completed_runs(rows)
    baseline = find_row(rows, "YOLO11n baseline")
    best = find_row(rows, "YOLO11n-P2-CoordAttention-960")
    server_time, server_status, train_process = read_server_snapshot()
    total_reports, ready_reports, partial_reports, pending_reports, missing_reports = dashboard_summary()

    best_map50 = to_float(best.get("best_map50", ""))
    best_map50_95 = to_float(best.get("best_map50_95", ""))
    base_map50 = to_float(baseline.get("best_map50", ""))
    base_map50_95 = to_float(baseline.get("best_map50_95", ""))
    delta_map50 = best_map50 - base_map50
    delta_map50_95 = best_map50_95 - base_map50_95

    lines = [
        "# 导师汇报简版",
        "",
        "本文档由 `tools/build_advisor_progress_brief.py` 生成，用于向导师简要说明 YOLO VisDrone 项目从工程实现推进到《计算机工程与应用》投稿准备的当前状态。它是汇报材料，不是论文正文；所有论文数值仍以 `paper/tables/`、训练日志、验证输出和审计文件为准。",
        "",
        "## 1. 研究目标",
        "",
        "本项目围绕 VisDrone2019-DET 无人机航拍目标检测任务，关注小目标占比高、目标密集、遮挡频繁和类别外观相似等问题。当前论文主线是以 Ultralytics YOLO11n 为轻量基线，评估 P2 高分辨率检测分支、CoordAttention、960 输入分辨率和小目标友好增强策略对检测精度、速度和复杂度的影响。",
        "",
        "## 2. 已完成实验和材料",
        "",
        f"- 已完成 100 epoch 本地训练/验证的模型数：{len(runs)}。",
    ]
    for run in runs:
        lines.append(
            f"- {run.model}：imgsz={run.imgsz}，best mAP50={run.best_map50:.5f}，best mAP50-95={run.best_map50_95:.5f}，结果目录 `{run.run_dir}`。"
        )

    lines.extend(
        [
            "",
            "## 3. 当前最强已完成模型",
            "",
            f"当前已完成实验中，`YOLO11n-P2-CoordAttention-960` 在 VisDrone 验证集上取得 best mAP50={best_map50:.5f}、best mAP50-95={best_map50_95:.5f}。与 `YOLO11n baseline` 的 best mAP50={base_map50:.5f}、best mAP50-95={base_map50_95:.5f} 相比，分别提升 {points(delta_map50)} 和 {points(delta_map50_95)}。",
            "",
            "需要注意：这一结论目前只说明当前已完成实验中的表现。由于 960 输入分辨率本身可能贡献较大，最终论文结论必须等待 YOLO11n-960、YOLO11n-P2-960、YOLOv8n-960、YOLO11s-960 等公平对比实验完成后再定稿。",
            "",
            "## 4. 小目标证据",
            "",
            f"- VisDrone YOLO 格式标注统计显示：训练集 small 目标占比 {scale_ratio('train', 'small')}，验证集 small 目标占比 {scale_ratio('val', 'small')}。",
            f"- 在 `conf=0.25`、`IoU=0.5` 的尺度分组匹配分析中，YOLO11n baseline 的 small 目标 recall 为 {scale_recall('YOLO11n baseline', 'small')}；YOLO11n-P2-CoordAttention-960 的 small 目标 recall 为 {scale_recall('YOLO11n-P2-CoordAttention-960', 'small')}。",
            "- 上述尺度分组结果用于分析不同尺度目标的匹配情况，不等同于官方 AP。",
            "",
            "## 5. 服务器公平对比实验",
            "",
            "为回答审稿人最可能追问的公平性问题，服务器正在按队列补跑以下实验：YOLO11n-960、YOLO11n-P2-960、YOLOv8n-960、YOLO11s-960、YOLOv5n-640。",
            f"- 最近服务器状态时间：{server_time}",
            f"- 当前 YOLO11n-960 状态：{server_status}",
            f"- 训练进程：`{train_process}`",
            "- 未完成 100 epoch 的服务器结果只作为进度信息，不能进入论文结果表、摘要或结论。",
            "",
            "## 6. 投稿准备状态",
            "",
            f"- 当前审计仪表盘：共 {total_reports} 个报告，{ready_reports} ready，{partial_reports} partial，{pending_reports} pending，{missing_reports} missing。",
            "- 已建立 LaTeX/PDF、图表、复现命令、证据审计、参考文献核验、投稿风险登记表和服务器状态追踪。",
            "- 当前核心阻塞仍是公平对比实验尚未全部完成；实验完成后需要同步完整日志和结果、重建表格、补测速度/复杂度，并按结果解释矩阵重写摘要、结果分析和结论。",
            "",
            "## 7. 给导师的风险说明",
            "",
            "- 目前不建议使用“全面优于主流 YOLO”这类绝对表述。",
            "- 如果 YOLO11n-960 接近主方法，论文应强调高分辨率输入是主要贡献来源，P2/CA 是结构补充。",
            "- 如果 YOLO11s-960 更强，论文应转向轻量化折中、参数效率和部署成本分析。",
            "- 如果新增对照结果整体不支持方法优势，论文仍可转为系统评估和实证分析型稿件，但必须如实呈现负结果。",
            "",
            "## 8. 下一步",
            "",
            "1. 等服务器公平对比实验完成 100 epoch。",
            "2. 用 `tools/sync_cea_server_results.ps1 -MinEpochs 100` 同步完整结果。",
            "3. 重新生成 `paper/tables/`、速度/复杂度/尺度分析和审计报告。",
            "4. 按 `paper/CEA_RESULT_INTERPRETATION_MATRIX.md` 重写论文主张。",
            "5. 编译 PDF，检查排版、引用、图表和数值追溯后再给导师审阅。",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    OUTPUT_PATH.write_text(build_brief(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
