from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = ROOT / "paper/CEA_OFFICIAL_REQUIREMENTS_TRACKER.md"


@dataclass
class SourceItem:
    sid: str
    source: str
    url: str
    authority: str
    use: str
    manual_check: str


SOURCES = [
    SourceItem(
        "S1",
        "CEA official template/download column candidate",
        "https://cea.ceaj.org/CN/column/column18.shtml",
        "official-candidate",
        "Use as the first place to verify the current writing template, download center, and submission instructions.",
        "Open manually before final submission and record the current template file, date, and required upload format.",
    ),
    SourceItem(
        "S2",
        "CEA editorial-office homepage candidate",
        "https://jsjgcyyy.juqk.net/",
        "official-candidate",
        "Use as a secondary route to confirm template, author submission entrance, and notices if the main official site is unavailable.",
        "Confirm that the site is the current editorial-office page before using any instruction from it.",
    ),
    SourceItem(
        "S3",
        "CEA submission notice candidate",
        "https://jsjgcyyy.juqk.net/buy/",
        "official-candidate",
        "Use only for manually checking submission notices, template reminders, originality/author responsibility wording, and system instructions.",
        "Do not copy requirements into the manuscript package until the page is manually verified near submission time.",
    ),
    SourceItem(
        "S4",
        "CCF WISA page mentioning CEA template URL",
        "https://ccf.org.cn/WISA2025/general_3015",
        "cross-reference",
        "Use only as supporting evidence that the CEA template URL may be used by a related Chinese-paper workflow.",
        "Do not treat conference page requirements as CEA journal requirements.",
    ),
    SourceItem(
        "S5",
        "Third-party CEA guide pages",
        "not fixed",
        "third-party",
        "Use only as weak background for common submission-process questions.",
        "Never treat third-party fee, cycle, template, or formatting claims as authoritative without official-site confirmation.",
    ),
]

MANUAL_FIELDS = [
    ("M1", "Template file", "Current official Word/LaTeX/PDF template file name, version/date, and download URL."),
    ("M2", "Upload file type", "Whether initial submission requires Word, PDF, source package, figures, or separate attachment files."),
    ("M3", "Author metadata", "Required author names, affiliations, corresponding author marker, email, phone, ORCID, postal address, and author order rules."),
    ("M4", "Declarations", "Required funding, acknowledgement, conflict-of-interest, data availability, ethics, copyright, or originality statements."),
    ("M5", "Length and format", "Required word/page count, Chinese/English title, abstracts, keywords, section style, figure/table style, and reference style."),
    ("M6", "Submission-system behavior", "Whether uploaded manuscripts can be replaced after submission and what manuscript ID/contact process is used."),
    ("M7", "Fees and attachments", "Any review fee, page fee, copyright transfer, membership discount, or signed document requirements."),
]


def write_report() -> None:
    lines = [
        "# CEA Official Requirements Tracker",
        "",
        "This file is generated by `tools/build_cea_official_requirements_tracker.py`.",
        "",
        "It tracks external requirement sources for the `Computer Engineering and Applications` submission route. Because journal websites and submission systems can change, this file records what must be manually verified before final upload. It is not itself proof of current official requirements.",
        "",
        "## Summary",
        "",
        f"- Total checks: {len(SOURCES) + len(MANUAL_FIELDS)}",
        f"- Ready: {len(SOURCES)}",
        f"- Pending: {len(MANUAL_FIELDS)}",
        "- Missing: 0",
        "",
        "## Source Candidates",
        "",
        "| ID | Source | URL | Authority | Use | Manual check |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item in SOURCES:
        lines.append(
            f"| {item.sid} | {item.source} | `{item.url}` | {item.authority} | {item.use} | {item.manual_check} |"
        )

    lines.extend(
        [
            "",
            "## Manual Requirement Fields",
            "",
            "| ID | Field | What to record before final upload | Status |",
            "| --- | --- | --- | --- |",
        ]
    )
    for mid, field, note in MANUAL_FIELDS:
        lines.append(f"| {mid} | {field} | {note} | PENDING |")

    lines.extend(
        [
            "",
            "## Use Rule",
            "",
            "- Official-candidate pages should be opened and checked manually close to the actual submission date.",
            "- Cross-reference pages can help locate a template URL but cannot define journal requirements.",
            "- Third-party pages are not authoritative and should not be cited as final submission rules.",
            "- Final manuscript and package changes must be made only after the official template/upload requirements are confirmed.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    write_report()
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
