from __future__ import annotations

import csv
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DASHBOARD_PATH = ROOT / "paper/ieee_submission_dashboard.md"


def read_text(rel_path: str) -> str:
    path = ROOT / rel_path
    if not path.exists():
        return ""
    return path.read_text(encoding="utf-8", errors="ignore")


def count_csv_rows(rel_path: str) -> int:
    path = ROOT / rel_path
    if not path.exists():
        return 0
    with path.open(newline="", encoding="utf-8-sig") as f:
        return sum(1 for _ in csv.DictReader(f))


def parse_summary(text: str) -> dict[str, str]:
    summary: dict[str, str] = {}
    for key in [
        "Total checks",
        "Ready",
        "Pending",
        "Missing",
        "Connection failed",
        "Tracked runs",
        "Partial",
        "Total entries",
        "Complete",
        "Ready in draft",
        "Non-ready numeric claims",
        "Untracked decimal tokens",
        "Untracked decimal tokens in draft",
    ]:
        match = re.search(rf"- {re.escape(key)}: ([^\n]+)", text)
        if match:
            summary[key] = match.group(1).strip()
    return summary


def extract_pending_rows(phase_audit: str) -> list[str]:
    rows: list[str] = []
    for line in phase_audit.splitlines():
        if "| " in line and "| PENDING |" in line:
            rows.append(line)
    return rows


def status_badge(value: str) -> str:
    if value in {"0", "0.0", "0 missing"}:
        return "OK"
    return value


def build_dashboard() -> str:
    phase_text = read_text("paper/ieee_phase1_artifact_audit.md")
    claim_text = read_text("paper/ieee_claim_audit.md")
    server_text = read_text("paper/ieee_server_progress_report.md")
    scale_text = read_text("paper/ieee_scale_output_audit.md")
    registry_text = read_text("paper/ieee_experiment_registry_audit.md")
    table_text = read_text("paper/ieee_table_audit.md")
    figure_text = read_text("paper/ieee_figure_audit.md")
    front_text = read_text("paper/ieee_front_matter_audit.md")
    number_text = read_text("paper/ieee_number_trace_audit.md")
    dataset_text = read_text("paper/ieee_dataset_compliance_audit.md")
    phase = parse_summary(phase_text)
    claim = parse_summary(claim_text)
    server = parse_summary(server_text)
    scale = parse_summary(scale_text)
    registry = parse_summary(registry_text)
    table = parse_summary(table_text)
    figure = parse_summary(figure_text)
    front = parse_summary(front_text)
    number = parse_summary(number_text)
    dataset = parse_summary(dataset_text)
    related_rows = count_csv_rows("paper/ieee_related_work_matrix.csv")
    section_rows = count_csv_rows("paper/ieee_trans/evidence_to_sections.csv")

    pending_rows = extract_pending_rows(phase_text)

    lines = [
        "# IEEE Submission Dashboard",
        "",
        "This dashboard is generated by `tools/build_ieee_submission_dashboard.py`. It summarizes the current IEEE Transactions route without treating planned or pending work as completed evidence.",
        "",
        "## Current Route",
        "",
        "- Active route: IEEE Transactions preparation.",
        "- Primary target framing: UAV-assisted traffic small-object detection, with T-ITS as the leading target direction.",
        "- Paused route: CEA Chinese journal/Word-template migration.",
        "- Manuscript status: planning skeleton exists; final IEEE `main.tex` is intentionally not created yet.",
        "",
        "## Readiness Snapshot",
        "",
        "| Area | Ready | Pending | Missing | Notes |",
        "| --- | ---: | ---: | ---: | --- |",
        (
            f"| Phase 1 artifacts | {phase.get('Ready', 'n/a')} | {phase.get('Pending', 'n/a')} | "
            f"{status_badge(phase.get('Missing', 'n/a'))} | `paper/ieee_phase1_artifact_audit.md` |"
        ),
        (
            f"| Claim audit | {claim.get('Ready', 'n/a')} | {claim.get('Pending', 'n/a')} | "
            f"{status_badge(claim.get('Missing', 'n/a'))} | `paper/ieee_claim_audit.md` |"
        ),
        (
            f"| Server progress | {server.get('Ready', 'n/a')} | {server.get('Partial', 'n/a')} partial / "
            f"{server.get('Connection failed', '0')} connection failed | "
            f"{server.get('Missing', 'n/a')} | `paper/ieee_server_progress_report.md` |"
        ),
        (
            f"| Scale-wise outputs | {scale.get('Ready', 'n/a')} | {scale.get('Pending', 'n/a')} | "
            f"{status_badge(scale.get('Missing', 'n/a'))} | `paper/ieee_scale_output_audit.md` |"
        ),
        (
            f"| Experiment registry | {registry.get('Complete', 'n/a')} complete | {registry.get('Pending', 'n/a')} | "
            f"{registry.get('Partial', '0')} partial | `paper/ieee_experiment_registry_audit.md` |"
        ),
        (
            f"| IEEE table drafts | {table.get('Ready', 'n/a')} | {table.get('Pending', 'n/a')} | "
            f"{status_badge(table.get('Missing', 'n/a'))} | `paper/ieee_table_audit.md` |"
        ),
        (
            f"| IEEE figure manifest | {figure.get('Ready', 'n/a')} | {figure.get('Pending', 'n/a')} | "
            f"{status_badge(figure.get('Missing', 'n/a'))} | `paper/ieee_figure_audit.md` |"
        ),
        (
            f"| Front matter audit | {front.get('Ready', 'n/a')} | {front.get('Pending', 'n/a')} | "
            f"{status_badge(front.get('Missing', 'n/a'))} | `paper/ieee_front_matter_audit.md` |"
        ),
        (
            f"| Number trace audit | {number.get('Ready in draft', 'n/a')} | "
            f"{number.get('Non-ready numeric claims', 'n/a')} | "
            f"{number.get('Untracked decimal tokens in draft', number.get('Untracked decimal tokens', 'n/a'))} untracked | `paper/ieee_number_trace_audit.md` |"
        ),
        (
            f"| Dataset compliance audit | {dataset.get('Ready', 'n/a')} | {dataset.get('Pending', 'n/a')} | "
            f"{status_badge(dataset.get('Missing', 'n/a'))} | `paper/ieee_dataset_compliance_audit.md` |"
        ),
        f"| Related-work matrix | {related_rows} rows | n/a | n/a | `paper/ieee_related_work_matrix.csv` |",
        f"| Evidence-to-section map | {section_rows} rows | n/a | n/a | `paper/ieee_trans/evidence_to_sections.csv` |",
        "",
        "## Ready Assets",
        "",
        "- IEEE route master plan: `paper/IEEE_TRANS_SUBMISSION_PLAN.md`",
        "- Target journal analysis: `paper/ieee_target_journal_analysis.md`",
        "- T-ITS scope-fit checklist: `paper/ieee_tits_scope_fit_checklist.md`",
        "- T-ITS author requirements audit: `paper/ieee_tits_author_requirements_audit.md`",
        "- Experiment gap matrix: `paper/ieee_required_experiment_gap.md`",
        "- Experiment registry: `paper/tables/ieee_experiment_registry.csv`, `paper/ieee_experiment_registry_audit.md`",
        "- Dataset strategy: `paper/ieee_dataset_strategy.md`",
        "- Method design and selection protocol: `paper/ieee_method_design_notes.md`, `paper/ieee_method_selection_protocol.md`",
        "- UAVDT setup and operational checklist: `paper/datasets/uavdt_setup.md`, `paper/datasets/uavdt_operational_checklist.md`",
        "- Claim boundary rules: `paper/ieee_claim_boundary.md`",
        "- Reviewer risk register and response-prep plan: `paper/ieee_reviewer_risk_register.md`, `paper/ieee_trans_response_plan.md`",
        "- Manuscript blueprint, front-matter/submission workbenches, section draft pack, assembly checklist, page budget plan, and main.tex preflight: `paper/ieee_trans/manuscript_blueprint.md`, `paper/ieee_trans/abstract_contribution_workbench.md`, `paper/ieee_trans/title_abstract_index_terms_workbench.md`, `paper/ieee_trans/submission_metadata_workbench.md`, `paper/ieee_trans/cover_letter_workbench.md`, `paper/ieee_trans/section_draft_pack.md`, `paper/ieee_trans/manuscript_assembly_checklist.md`, `paper/ieee_trans/page_budget_plan.md`, `paper/ieee_trans/main_tex_preflight.md`",
        "- Related-work outline and literature comparison protocol: `paper/ieee_trans/related_work_outline.md`, `paper/ieee_literature_comparison_protocol.md`, `paper/tables/ieee_literature_context.csv`",
        "- Seed bibliography, citation plan, and reference-gap report: `paper/ieee_trans/references_seed.bib`, `paper/ieee_trans/citation_plan.md`, `paper/ieee_reference_gap_report.md`",
        "- Table/figure plan: `paper/ieee_trans/table_figure_plan.md`",
        "- Generated IEEE table drafts and audit: `paper/ieee_trans/tables/`, `paper/ieee_table_audit.md`",
        "- Figure source manifest and audit: `paper/ieee_trans/figure_source_manifest.md`, `paper/ieee_figure_audit.md`",
        "- Front-matter audit for T-ITS title, abstract, index terms, and metadata: `paper/ieee_front_matter_audit.md`",
        "- Number trace audit for draft paragraphs: `paper/ieee_number_trace_audit.md`",
        "- Dataset license and compliance audits: `paper/ieee_dataset_license_audit.md`, `paper/ieee_dataset_compliance_audit.md`",
        "- Server integration protocol: `paper/IEEE_RESULT_INTEGRATION_PROTOCOL.md`",
        "- Scale-wise evaluation protocol, local AP protocol, audits, and interpretations: `paper/ieee_scale_evaluation_protocol.md`, `paper/ieee_scale_ap_protocol.md`, `paper/ieee_scale_output_audit.md`, `paper/ieee_scale_result_interpretation.md`, `paper/ieee_scale_ap_interpretation.md`",
        "- Guarded server queue: `tools/run_ieee_server_queue.sh`",
        "- Guarded server sync/status tools: `tools/check_ieee_server_status.ps1`, `tools/sync_ieee_server_results.ps1`",
        "",
        "## Current Pending Gates",
        "",
    ]

    if pending_rows:
        lines.extend(
            [
                "| Area | Item | Status | Evidence | Action |",
                "| --- | --- | --- | --- | --- |",
            ]
        )
        lines.extend(pending_rows)
    else:
        lines.append("No pending gates recorded in the latest Phase 1 audit.")

    lines.extend(
        [
            "",
            "## Next Execution Order",
            "",
            "1. Check server status with `tools/check_ieee_server_status.ps1` when SSH key access is available.",
            "2. If TOFC or UAVDT runs are complete, sync only complete artifacts with `tools/sync_ieee_server_results.ps1 -MinEpochs 100`.",
            "3. Run `python tools/run_ieee_audits.py` after every result sync or table/figure update.",
            "4. Use the completed VisDrone scale-wise recall/precision and local scale-bin AP outputs for small-object discussion; rerun them only after adding new final-model weights.",
            "5. Keep the T-ITS traffic-sensing framing aligned with `paper/ieee_tits_scope_fit_checklist.md`.",
            "6. Convert and validate UAVDT before writing generalization claims.",
            "7. Draft final IEEE `main.tex` only after the main method and evidence gates are settled.",
            "",
            "## Claim Discipline",
            "",
            "- TOFC is a candidate design until full result evidence exists.",
            "- UAVDT is a planned second dataset until conversion and runs are complete.",
            "- Existing VisDrone results can be discussed only with exact values from audited tables.",
            "- Larger YOLO11s accuracy must be acknowledged; the safe current narrative is lightweight trade-off, not universal superiority.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    DASHBOARD_PATH.write_text(build_dashboard(), encoding="utf-8")
    print(f"Wrote {DASHBOARD_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
