from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT_PATH = ROOT / "paper/tables/ieee_scale_ap_results_visdrone.csv"
OUTPUT_PATH = ROOT / "paper/ieee_scale_ap_interpretation.md"
BASELINE = "YOLO11n-960"
SCALE_ORDER = ["small", "medium", "large"]


def read_rows() -> list[dict[str, str]]:
    if not INPUT_PATH.exists():
        return []
    with INPUT_PATH.open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def f6(value: float) -> str:
    return f"{value:.6f}"


def pct(value: float) -> str:
    return f"{value * 100:.2f} percentage points"


def by_model_scale(rows: list[dict[str, str]]) -> dict[tuple[str, str], dict[str, str]]:
    return {(row["model"], row["scale"]): row for row in rows}


def build_report(rows: list[dict[str, str]]) -> str:
    if not rows:
        return "\n".join(
            [
                "# IEEE Local Scale-Bin AP Interpretation",
                "",
                f"No rows found at `{INPUT_PATH.relative_to(ROOT)}`.",
                "",
            ]
        )

    lookup = by_model_scale(rows)
    models: list[str] = []
    for row in rows:
        if row["model"] not in models:
            models.append(row["model"])

    lines = [
        "# IEEE Local Scale-Bin AP Interpretation",
        "",
        "This report is generated by `tools/build_ieee_scale_ap_interpretation.py` from `paper/tables/ieee_scale_ap_results_visdrone.csv`.",
        "",
        "It reports local scale-bin AP diagnostics only. It is not an official COCO or VisDrone AP-small/AP-medium/AP-large evaluation.",
        "",
        "## Source",
        "",
        f"- Source CSV: `{INPUT_PATH.relative_to(ROOT)}`",
        "- Dataset: VisDrone2019-DET validation split",
        "- Prediction scale policy: same-bin, as recorded in the source CSV",
        "- NMS confidence: 0.001; NMS IoU: 0.7; max detections: 300",
        "",
        "## Local Scale-Bin AP",
        "",
        "| Model | Scale | GT | AP50 | mAP50-95 |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    for model in models:
        for scale in SCALE_ORDER:
            row = lookup.get((model, scale))
            if not row:
                continue
            lines.append(
                f"| {model} | {scale} | {row['gt_instances']} | {row['ap50']} | {row['map50_95']} |"
            )

    lines.extend(
        [
            "",
            f"## Delta vs {BASELINE}",
            "",
            "| Model | Small AP50 Delta | Small mAP50-95 Delta | Medium AP50 Delta | Large AP50 Delta |",
            "| --- | ---: | ---: | ---: | ---: |",
        ]
    )

    base_small = lookup[(BASELINE, "small")]
    base_medium = lookup[(BASELINE, "medium")]
    base_large = lookup[(BASELINE, "large")]
    base_small_ap50 = float(base_small["ap50"])
    base_small_map = float(base_small["map50_95"])
    base_medium_ap50 = float(base_medium["ap50"])
    base_large_ap50 = float(base_large["ap50"])

    for model in models:
        small = lookup[(model, "small")]
        medium = lookup[(model, "medium")]
        large = lookup[(model, "large")]
        lines.append(
            "| "
            + model
            + " | "
            + f6(float(small["ap50"]) - base_small_ap50)
            + " | "
            + f6(float(small["map50_95"]) - base_small_map)
            + " | "
            + f6(float(medium["ap50"]) - base_medium_ap50)
            + " | "
            + f6(float(large["ap50"]) - base_large_ap50)
            + " |"
        )

    p2_small_ap50_delta = float(lookup[("YOLO11n-P2-960", "small")]["ap50"]) - base_small_ap50
    p2_small_map_delta = float(lookup[("YOLO11n-P2-960", "small")]["map50_95"]) - base_small_map
    p2ca_small_ap50_delta = float(lookup[("YOLO11n-P2-CA-960", "small")]["ap50"]) - base_small_ap50
    y11s_small_ap50_delta = float(lookup[("YOLO11s-960", "small")]["ap50"]) - base_small_ap50

    lines.extend(
        [
            "",
            "## Evidence-Bounded Interpretation",
            "",
            f"- Compared with YOLO11n-960, YOLO11n-P2-960 improves local small-bin AP50 by `{f6(p2_small_ap50_delta)}` ({pct(p2_small_ap50_delta)}) and local small-bin mAP50-95 by `{f6(p2_small_map_delta)}` ({pct(p2_small_map_delta)}).",
            f"- YOLO11n-P2-CA-960 improves local small-bin AP50 by `{f6(p2ca_small_ap50_delta)}` ({pct(p2ca_small_ap50_delta)}) over YOLO11n-960, but remains below YOLO11n-P2-960 in this diagnostic.",
            f"- YOLO11s-960 remains the strongest local small-bin AP50 reference, with a `{f6(y11s_small_ap50_delta)}` ({pct(y11s_small_ap50_delta)}) gain over YOLO11n-960.",
            "- Medium and large bins show trade-offs for the P2 variants, so the result should not be described as a uniform all-scale improvement.",
            "- Use the phrase local scale-bin AP. Do not call this official AP-small.",
            "",
            "## Manuscript Use",
            "",
            "Allowed wording:",
            "",
            "> A local scale-bin AP diagnostic further supports the small-object trend: YOLO11n-P2-960 improves small-bin AP50 over YOLO11n-960, while larger YOLO11s-960 remains the strongest completed reference.",
            "",
            "Avoid wording:",
            "",
            "- `The method improves official AP-small`.",
            "- `The method improves all scale groups`.",
            "- `The lightweight model is better than YOLO11s`.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    rows = read_rows()
    OUTPUT_PATH.write_text(build_report(rows), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
