from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT_PATH = ROOT / "paper/tables/ieee_scale_results_visdrone.csv"
OUTPUT_PATH = ROOT / "paper/ieee_scale_result_interpretation.md"
BASELINE = "YOLO11n-960"
SCALE_ORDER = ["small", "medium", "large"]


def read_rows() -> list[dict[str, str]]:
    if not INPUT_PATH.exists():
        return []
    with INPUT_PATH.open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def f6(value: float) -> str:
    return f"{value:.6f}"


def pct(value: float) -> str:
    return f"{value * 100:.2f} percentage points"


def by_model_scale(rows: list[dict[str, str]]) -> dict[tuple[str, str], dict[str, str]]:
    return {(row["model"], row["scale"]): row for row in rows}


def build_report(rows: list[dict[str, str]]) -> str:
    if not rows:
        return "\n".join(
            [
                "# IEEE Scale-Wise Result Interpretation",
                "",
                f"No rows found at `{INPUT_PATH.relative_to(ROOT)}`.",
                "",
            ]
        )

    lookup = by_model_scale(rows)
    models: list[str] = []
    for row in rows:
        if row["model"] not in models:
            models.append(row["model"])

    lines = [
        "# IEEE Scale-Wise Result Interpretation",
        "",
        "This report is generated by `tools/build_ieee_scale_interpretation.py` from `paper/tables/ieee_scale_results_visdrone.csv`.",
        "",
        "It interprets scale-wise recall/precision only. It does not report AP-small/AP-medium/AP-large.",
        "",
        "## Source",
        "",
        f"- Source CSV: `{INPUT_PATH.relative_to(ROOT)}`",
        "- Dataset: VisDrone2019-DET validation split",
        "- Scale bins: small `<32x32`, medium `[32x32,96x96)`, large `>=96x96` based on GT box area",
        "- Matching: confidence 0.25, IoU 0.5, max detections 300, as recorded in the source CSV",
        "",
        "## Scale-Wise Recall and Precision",
        "",
        "| Model | Scale | GT | Recall | Precision |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    for model in models:
        for scale in SCALE_ORDER:
            row = lookup.get((model, scale))
            if not row:
                continue
            lines.append(
                f"| {model} | {scale} | {row['gt_instances']} | {row['recall']} | {row['precision']} |"
            )

    lines.extend(
        [
            "",
            f"## Delta vs {BASELINE}",
            "",
            "| Model | Small Recall Delta | Small Precision Delta | Medium Recall Delta | Large Recall Delta |",
            "| --- | ---: | ---: | ---: | ---: |",
        ]
    )

    base_small = lookup[(BASELINE, "small")]
    base_medium = lookup[(BASELINE, "medium")]
    base_large = lookup[(BASELINE, "large")]
    base_small_recall = float(base_small["recall"])
    base_small_precision = float(base_small["precision"])
    base_medium_recall = float(base_medium["recall"])
    base_large_recall = float(base_large["recall"])

    for model in models:
        small = lookup[(model, "small")]
        medium = lookup[(model, "medium")]
        large = lookup[(model, "large")]
        lines.append(
            "| "
            + model
            + " | "
            + f6(float(small["recall"]) - base_small_recall)
            + " | "
            + f6(float(small["precision"]) - base_small_precision)
            + " | "
            + f6(float(medium["recall"]) - base_medium_recall)
            + " | "
            + f6(float(large["recall"]) - base_large_recall)
            + " |"
        )

    p2_small_delta = float(lookup[("YOLO11n-P2-960", "small")]["recall"]) - base_small_recall
    p2ca_small_delta = float(lookup[("YOLO11n-P2-CA-960", "small")]["recall"]) - base_small_recall
    y11s_small_delta = float(lookup[("YOLO11s-960", "small")]["recall"]) - base_small_recall

    lines.extend(
        [
            "",
            "## Evidence-Bounded Interpretation",
            "",
            f"- Compared with YOLO11n-960, YOLO11n-P2-960 improves small-object recall by `{f6(p2_small_delta)}` ({pct(p2_small_delta)}).",
            f"- YOLO11n-P2-CA-960 improves small-object recall by `{f6(p2ca_small_delta)}` ({pct(p2ca_small_delta)}) over YOLO11n-960.",
            f"- YOLO11s-960 remains the strongest small-object recall reference, with a `{f6(y11s_small_delta)}` ({pct(y11s_small_delta)}) recall gain over YOLO11n-960.",
            "- P2/CA improves small-scale recall on VisDrone validation, but the medium/large-scale rows show trade-offs rather than uniform gains across all scales.",
            "- The correct wording is scale-wise recall/precision improvement, not AP-small improvement.",
            "- These results support the lightweight trade-off narrative, not a claim that the nano model outperforms larger-capacity detectors.",
            "",
            "## Manuscript Use",
            "",
            "Allowed wording:",
            "",
            "> On the VisDrone validation split, scale-wise analysis shows that the P2 high-resolution branch increases small-object recall compared with the YOLO11n-960 baseline, while YOLO11s-960 remains stronger in absolute recall. This suggests that high-resolution shallow prediction helps lightweight models recover small objects, but larger capacity still provides a higher upper reference.",
            "",
            "Avoid wording:",
            "",
            "- `The method improves AP-small` unless AP-specific evaluation is added.",
            "- `The lightweight model is best across all scales`.",
            "- `The method outperforms YOLO11s`.",
            "- `The result proves cross-dataset generalization`.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    rows = read_rows()
    OUTPUT_PATH.write_text(build_report(rows), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
