from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = ROOT / "paper/submission_audit_dashboard.md"


AUDIT_REPORTS = [
    ("Submission readiness", "paper/submission_readiness_audit.md"),
    ("Goal completion", "paper/GOAL_COMPLETION_AUDIT.md"),
    ("Journal manuscript gaps", "paper/manuscript_journal_gap_audit.md"),
    ("Paper consistency", "paper/paper_consistency_audit.md"),
    ("Claim boundaries", "paper/claim_boundary_audit.md"),
    ("Result interpretation matrix", "paper/result_interpretation_matrix_audit.md"),
    ("Evidence audit", "paper/evidence_audit.md"),
    ("Manuscript number trace", "paper/manuscript_number_trace_audit.md"),
    ("Manuscript length", "paper/manuscript_length_audit.md"),
    ("Section evidence map", "paper/section_evidence_map_audit.md"),
    ("Submission risk register", "paper/submission_risk_register_audit.md"),
    ("CEA reviewer response prep", "paper/cea_reviewer_response_prep_audit.md"),
    ("CEA post-result rewrite playbook", "paper/cea_post_result_rewrite_playbook_audit.md"),
    ("CEA official requirements tracker", "paper/cea_official_requirements_tracker_audit.md"),
    ("CEA Word migration", "paper/cea_template_migration/cea_word_migration_audit.md"),
    ("LaTeX references", "paper/tex_reference_audit.md"),
    ("Reference verification", "paper/reference_verification_audit.md"),
    ("LaTeX figures", "paper/tex_figure_audit.md"),
    ("LaTeX cross references", "paper/tex_cross_reference_audit.md"),
    ("LaTeX table sources", "paper/tex_table_source_audit.md"),
    ("Reproducibility commands", "paper/repro_commands_audit.md"),
    ("Config inventory", "paper/config_inventory_audit.md"),
    ("Text hygiene", "paper/text_hygiene_audit.md"),
    ("Project README presentation", "paper/project_readme_presentation_audit.md"),
    ("GitHub public view", "paper/github_public_view_audit.md"),
    ("PDF text readability", "paper/pdf_text_readability_audit.md"),
    ("PDF layout health", "paper/pdf_layout_health_audit.md"),
    ("Advisor progress brief", "paper/advisor_progress_brief_audit.md"),
    ("CEA submission package checklist", "paper/CEA_SUBMISSION_PACKAGE_CHECKLIST.md"),
    ("CEA manual submission preflight", "paper/CEA_MANUAL_SUBMISSION_PREFLIGHT.md"),
    ("Synced fair-experiment artifacts", "paper/synced_fair_experiment_artifacts_audit.md"),
    ("Post-sync update checklist", "paper/post_sync_update_checklist.md"),
    ("Server status snapshot", "paper/cea_server_status_snapshot.md"),
]


@dataclass
class AuditSummary:
    name: str
    path: str
    status: str
    summary: str
    note: str = ""


def parse_summary(text: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for key in ["Total checks", "Ready", "Partial", "Pending", "Missing"]:
        match = re.search(rf"- {re.escape(key)}:\s*([0-9]+)", text)
        if match:
            values[key] = match.group(1)
    return values


def summarize_report(name: str, rel_path: str) -> AuditSummary:
    path = ROOT / rel_path
    if not path.exists():
        return AuditSummary(name, rel_path, "MISSING", "report file not found", "Generate the report.")

    text = path.read_text(encoding="utf-8-sig")
    values = parse_summary(text)
    if values:
        summary = ", ".join(f"{k}={v}" for k, v in values.items())
        missing = int(values.get("Missing", "0"))
        pending = int(values.get("Pending", "0"))
        partial = int(values.get("Partial", "0"))
        if missing:
            status = "MISSING"
        elif pending:
            status = "PENDING"
        elif partial:
            status = "PARTIAL"
        else:
            status = "READY"
        return AuditSummary(name, rel_path, status, summary)

    if name == "Evidence audit":
        status = "READY" if "No official VisDrone test-dev/test-challenge AP is available yet" in text else "PARTIAL"
        return AuditSummary(name, rel_path, status, "narrative evidence audit", "Review manually for number provenance.")

    if name == "Server status snapshot":
        match = re.search(r"baseline_yolo11n_960_visdrone \| PARTIAL \| ([0-9]+)", text)
        if match:
            return AuditSummary(name, rel_path, "PENDING", f"YOLO11n-960 partial at {match.group(1)} epochs")
        return AuditSummary(name, rel_path, "READY", "server snapshot generated")

    return AuditSummary(name, rel_path, "READY", "report exists")


def write_dashboard(summaries: list[AuditSummary]) -> None:
    total = len(summaries)
    ready = sum(1 for s in summaries if s.status == "READY")
    partial = sum(1 for s in summaries if s.status == "PARTIAL")
    pending = sum(1 for s in summaries if s.status == "PENDING")
    missing = sum(1 for s in summaries if s.status == "MISSING")

    lines = [
        "# Submission Audit Dashboard",
        "",
        "This dashboard is generated by `tools/build_submission_audit_dashboard.py`. It summarizes paper-facing audit reports so the project status can be reviewed quickly without opening every individual report.",
        "",
        "## Summary",
        "",
        f"- Total audit reports: {total}",
        f"- Ready reports: {ready}",
        f"- Partial reports: {partial}",
        f"- Pending reports: {pending}",
        f"- Missing reports: {missing}",
        "",
        "## Reports",
        "",
        "| Audit | Status | Summary | Path | Note |",
        "| --- | --- | --- | --- | --- |",
    ]
    for s in summaries:
        lines.append(f"| {s.name} | {s.status} | {s.summary} | `{s.path}` | {s.note} |")

    fair_artifacts = next((s for s in summaries if s.name == "Synced fair-experiment artifacts"), None)
    if fair_artifacts and fair_artifacts.status == "READY":
        current_gate = (
            "Fair-comparison experiments have been synchronized and traced to local artifacts. "
            "The remaining submission gates are journal-format/manual preflight items, final visual PDF inspection, "
            "author metadata, and official VisDrone test-dev results if the platform becomes usable."
        )
    else:
        current_gate = (
            "The project is not yet final-submission-ready while fair-comparison experiments remain pending. "
            "Partial server runs are progress information only and must not be copied into paper result tables."
        )

    lines.extend(
        [
            "",
            "## Current Gate",
            "",
            current_gate,
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    summaries = [summarize_report(name, path) for name, path in AUDIT_REPORTS]
    write_dashboard(summaries)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
