from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TABLE_DIR = ROOT / "paper/ieee_trans/tables"
REPORT_PATH = ROOT / "paper/ieee_table_audit.md"

REQUIRED_TABLES = [
    "visdrone_main_results.tex",
    "speed_complexity.tex",
    "scale_recall_precision.tex",
    "scale_bin_ap.tex",
    "literature_context.tex",
    "README.md",
]

FORBIDDEN_PATTERNS = [
    re.compile(r"TODO", re.I),
    re.compile("\u5f85\u8865\u5145"),
    re.compile(r"AP-small", re.I),
]


@dataclass
class TableCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_label(status: str) -> str:
    return {
        "ready": "READY",
        "pending": "PENDING",
        "missing": "MISSING",
    }[status]


def count_columns(line: str) -> int:
    return line.count("&") + 1


def check_table_columns(path: Path) -> TableCheck:
    text = path.read_text(encoding="utf-8", errors="ignore")
    lines = [line.strip() for line in text.splitlines()]
    content_rows = [line for line in lines if "&" in line and line.endswith(r"\\")]
    if not content_rows:
        return TableCheck(path.name, "missing", "no tabular rows found", "Regenerate IEEE tables.")

    expected = count_columns(content_rows[0])
    bad_rows = [
        index + 1
        for index, row in enumerate(content_rows)
        if count_columns(row) != expected
    ]
    if bad_rows:
        return TableCheck(
            path.name,
            "missing",
            f"column mismatch at row indices {bad_rows}",
            "Fix exporter or table source.",
        )
    return TableCheck(path.name, "ready", f"{len(content_rows)} rows, {expected} columns")


def audit() -> list[TableCheck]:
    checks: list[TableCheck] = []
    for name in REQUIRED_TABLES:
        path = TABLE_DIR / name
        if not path.exists():
            checks.append(
                TableCheck(
                    name,
                    "missing",
                    str(path.relative_to(ROOT)),
                    "Run tools/export_ieee_tables.py.",
                )
            )
            continue
        checks.append(TableCheck(f"File exists: {name}", "ready", str(path.relative_to(ROOT))))
        if name.endswith(".tex"):
            checks.append(check_table_columns(path))
            text = path.read_text(encoding="utf-8", errors="ignore")
            hits = [pattern.pattern for pattern in FORBIDDEN_PATTERNS if pattern.search(text)]
            checks.append(
                TableCheck(
                    f"Forbidden markers: {name}",
                    "ready" if not hits else "missing",
                    "none" if not hits else ", ".join(hits),
                    "" if not hits else "Remove placeholder or AP-small wording from generated table.",
                )
            )
    return checks


def write_report(checks: list[TableCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    pending = sum(1 for c in checks if c.status == "pending")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# IEEE Table Audit",
        "",
        "This report is generated by `tools/check_ieee_tables.py`. It checks generated IEEE LaTeX table drafts for existence, simple column consistency, and placeholder wording.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Pending: {pending}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for check in checks:
        lines.append(
            f"| {check.item} | {status_label(check.status)} | `{check.evidence}` | {check.action} |"
        )
    lines.append("")
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
