param(
    [string]$HostName = "connect.bjb2.seetacloud.com",
    [int]$Port = 44733,
    [string]$User = "root",
    [string]$IdentityFile = "$env:USERPROFILE\.ssh\autodl_yolo_visdrone",
    [string]$RemoteRoot = "/root/autodl-tmp/yolo-visdrone-project",
    [int]$MinEpochs = 100,
    [string]$OutputPath = "paper\ieee_server_status_snapshot.md",
    [string]$HistoryPath = "paper\tables\ieee_server_status_history.csv",
    [string[]]$RunNames = @(
        "yolo11n_p2_tofc_960_visdrone",
        "baseline_yolo11n_960_uavdt",
        "yolo11n_p2_960_uavdt",
        "baseline_yolov8n_960_uavdt",
        "baseline_yolo11s_960_uavdt"
    )
)

$ErrorActionPreference = "Stop"

$sshTarget = "$User@$HostName"
$sshArgs = @(
    "-i", $IdentityFile,
    "-p", "$Port",
    "-o", "StrictHostKeyChecking=no",
    "-o", "ConnectTimeout=10",
    "-o", "BatchMode=yes",
    $sshTarget
)
$scpArgs = @(
    "-i", $IdentityFile,
    "-P", "$Port",
    "-o", "StrictHostKeyChecking=no",
    "-o", "ConnectTimeout=10",
    "-o", "BatchMode=yes"
)

$remoteScript = @'
remote_root="$1"
min_epochs="$2"
shift 2

cd "$remote_root" || exit 1

printf "REMOTE_ROOT|%s\n" "$remote_root"
printf "MIN_EPOCHS|%s\n" "$min_epochs"

for run_name in "$@"; do
  run_dir="runs/detect/$run_name"
  results="$run_dir/results.csv"
  args="$run_dir/args.yaml"
  best="$run_dir/weights/best.pt"

  if [ ! -f "$results" ]; then
    printf "RUN|%s|MISSING|0||||%s|%s\n" "$run_name" "$args" "$best"
    continue
  fi

  lines=$(wc -l < "$results")
  epochs=$((lines - 1))
  last=$(tail -1 "$results")
  last_epoch=$(printf "%s" "$last" | cut -d, -f1)
  final_map50=$(printf "%s" "$last" | cut -d, -f13)
  final_map5095=$(printf "%s" "$last" | cut -d, -f14)
  if [ "$epochs" -ge "$min_epochs" ]; then
    status="READY"
  else
    status="PARTIAL"
  fi

  printf "RUN|%s|%s|%s|%s|%s|%s|%s|%s\n" "$run_name" "$status" "$epochs" "$last_epoch" "$final_map50" "$final_map5095" "$args" "$best"
done

scale_csv="paper/tables/ieee_scale_results_visdrone.csv"
scale_fig="paper/figures/scale_analysis/ieee_scale_recall_visdrone.png"
if [ -f "$scale_csv" ]; then
  rows=$(($(wc -l < "$scale_csv") - 1))
  printf "SCALE|READY|%s|%s\n" "$scale_csv" "$rows"
else
  printf "SCALE|MISSING|%s|0\n" "$scale_csv"
fi
if [ -f "$scale_fig" ]; then
  bytes=$(wc -c < "$scale_fig")
  printf "SCALE_FIG|READY|%s|%s\n" "$scale_fig" "$bytes"
else
  printf "SCALE_FIG|MISSING|%s|0\n" "$scale_fig"
fi

proc_state=$(ps -eo pid=,stat=,etime=,pcpu=,cmd= 2>/dev/null | grep -E 'run_ieee_server_queue|train_baseline.py|evaluate_scale_groups.py' | grep -v grep || true)
if [ -n "$proc_state" ]; then
  printf "%s\n" "$proc_state" | while IFS= read -r proc_line; do
    safe_line=$(printf "%s" "$proc_line" | tr '|' '/')
    printf "PROC|%s\n" "$safe_line"
  done
else
  printf "PROC|NO_MATCHING_PROCESS\n"
fi
'@

$tmpLocal = [System.IO.Path]::GetTempFileName()
$remoteTmp = "/tmp/ieee_check_server_status_$PID.sh"

function Write-ConnectionFailure {
    param([string]$Message)

    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"
    $repoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")

    if (![string]::IsNullOrWhiteSpace($OutputPath)) {
        $outputFullPath = Join-Path $repoRoot $OutputPath
        $outputDir = Split-Path $outputFullPath -Parent
        New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

        $report = New-Object System.Collections.Generic.List[string]
        $report.Add("# IEEE Server Status Snapshot")
        $report.Add("")
        $report.Add("Generated by ``tools/check_ieee_server_status.ps1`` at " + $timestamp + ".")
        $report.Add("")
        $report.Add("- Remote root: ``" + $RemoteRoot + "``")
        $report.Add("- Completion gate: ``" + $MinEpochs + "`` epochs")
        $report.Add("- Status: ``CONNECTION_FAILED``")
        $report.Add("- Error: ``" + ($Message -replace "\|", "/") + "``")
        $report.Add("- Evidence rule: no remote run status was verified, and no manuscript-facing result may be inferred from this check.")
        $report.Add("")
        $report.Add("## Runs")
        $report.Add("")
        $report.Add("| Run | Status | Epochs | Last Epoch | Last mAP50 | Last mAP50-95 | Args | Best |")
        $report.Add("| --- | --- | ---: | ---: | ---: | ---: | --- | --- |")
        foreach ($runName in $RunNames) {
            $report.Add("| " + $runName + " | CONNECTION_FAILED | 0 |  |  |  |  |  |")
        }
        $report.Add("")
        $report.Add("## Processes")
        $report.Add("")
        $report.Add("| State |")
        $report.Add("| --- |")
        $report.Add("| ``status check failed before remote process inspection`` |")
        $report | Set-Content -Path $outputFullPath -Encoding UTF8
        Write-Host "Wrote connection-failure snapshot: $outputFullPath"
    }

    if (![string]::IsNullOrWhiteSpace($HistoryPath)) {
        $historyFullPath = Join-Path $repoRoot $HistoryPath
        $historyDir = Split-Path $historyFullPath -Parent
        New-Item -ItemType Directory -Force -Path $historyDir | Out-Null

        $historyRows = foreach ($runName in $RunNames) {
            [pscustomobject]@{
                timestamp = $timestamp
                remote_root = $RemoteRoot
                completion_gate_epochs = $MinEpochs
                run = $runName
                status = "CONNECTION_FAILED"
                epochs = 0
                last_epoch = ""
                last_map50 = ""
                last_map50_95 = ""
                args = ""
                best = ""
                processes = "status check failed: " + ($Message -replace "\|", "/")
            }
        }
        if (Test-Path -LiteralPath $historyFullPath) {
            $historyRows | Export-Csv -Path $historyFullPath -NoTypeInformation -Encoding UTF8 -Append
        }
        else {
            $historyRows | Export-Csv -Path $historyFullPath -NoTypeInformation -Encoding UTF8
        }
        Write-Host "Appended connection-failure history: $historyFullPath"
    }
}

try {
    $scriptForSsh = ($remoteScript -replace "`r", "") + "`n"
    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($tmpLocal, $scriptForSsh, $utf8NoBom)

    & scp @scpArgs $tmpLocal "${sshTarget}:$remoteTmp" | Out-Null
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to copy temporary status script to server."
    }

    $runArgs = $RunNames -join " "
    $remoteRunCommand = "bash '$remoteTmp' '$RemoteRoot' '$MinEpochs' $runArgs; status=`$?; rm -f '$remoteTmp'; exit `$status"
    $rawLines = & ssh @sshArgs $remoteRunCommand
    if ($LASTEXITCODE -ne 0) {
        throw "SSH status check failed with exit code $LASTEXITCODE"
    }
}
catch {
    Write-ConnectionFailure -Message $_.Exception.Message
    throw
}
finally {
    if (Test-Path -LiteralPath $tmpLocal) {
        Remove-Item -LiteralPath $tmpLocal -Force
    }
}

$displayLines = New-Object System.Collections.Generic.List[string]
$runRows = New-Object System.Collections.Generic.List[object]
$procRows = New-Object System.Collections.Generic.List[object]
$scaleRows = New-Object System.Collections.Generic.List[object]
$remoteRootValue = ""
$minEpochsValue = "$MinEpochs"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"

foreach ($line in $rawLines) {
    if ([string]::IsNullOrWhiteSpace($line)) {
        continue
    }

    $parts = $line -split "\|"
    switch ($parts[0]) {
        "REMOTE_ROOT" {
            $remoteRootValue = $parts[1]
            $displayLines.Add("Remote root: $($parts[1])")
        }
        "MIN_EPOCHS" {
            $minEpochsValue = $parts[1]
            $displayLines.Add("Completion gate: $($parts[1]) epochs")
            $displayLines.Add("")
        }
        "RUN" {
            $runName = $parts[1]
            $status = $parts[2]
            $epochs = $parts[3]
            $lastEpoch = $parts[4]
            $map50 = $parts[5]
            $map5095 = $parts[6]
            $argsPath = $parts[7]
            $bestPath = $parts[8]

            if ($status -eq "READY") {
                $displayLines.Add("[READY]   $runName epochs=$epochs last_epoch=$lastEpoch mAP50=$map50 mAP50-95=$map5095")
            }
            elseif ($status -eq "PARTIAL") {
                $displayLines.Add("[PARTIAL] $runName epochs=$epochs last_epoch=$lastEpoch mAP50=$map50 mAP50-95=$map5095")
            }
            else {
                $displayLines.Add("[MISSING] $runName")
            }
            $displayLines.Add("          args=$argsPath")
            $displayLines.Add("          best=$bestPath")
            $runRows.Add([pscustomobject]@{
                Run = $runName
                Status = $status
                Epochs = $epochs
                LastEpoch = $lastEpoch
                LastMap50 = $map50
                LastMap5095 = $map5095
                Args = $argsPath
                Best = $bestPath
            })
        }
        "SCALE" {
            $displayLines.Add("[SCALE]   $($parts[1]) $($parts[2]) rows=$($parts[3])")
            $scaleRows.Add([pscustomobject]@{
                Item = "scale_csv"
                Status = $parts[1]
                Path = $parts[2]
                Detail = $parts[3]
            })
        }
        "SCALE_FIG" {
            $displayLines.Add("[SCALE_FIG] $($parts[1]) $($parts[2]) bytes=$($parts[3])")
            $scaleRows.Add([pscustomobject]@{
                Item = "scale_figure"
                Status = $parts[1]
                Path = $parts[2]
                Detail = $parts[3]
            })
        }
        "PROC" {
            $state = ($parts[1..($parts.Length - 1)] -join "|")
            $displayLines.Add("Process: $state")
            $procRows.Add([pscustomobject]@{
                State = $state
            })
        }
    }
}

foreach ($displayLine in $displayLines) {
    Write-Host $displayLine
}

if (![string]::IsNullOrWhiteSpace($OutputPath)) {
    $outputFullPath = Join-Path (Resolve-Path (Join-Path $PSScriptRoot "..")) $OutputPath
    $outputDir = Split-Path $outputFullPath -Parent
    New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

    $report = New-Object System.Collections.Generic.List[string]
    $report.Add("# IEEE Server Status Snapshot")
    $report.Add("")
    $report.Add("Generated by ``tools/check_ieee_server_status.ps1`` at " + $timestamp + ".")
    $report.Add("")
    $report.Add("- Remote root: ``" + $remoteRootValue + "``")
    $report.Add("- Completion gate: ``" + $minEpochsValue + "`` epochs")
    $report.Add("- Evidence rule: partial or missing runs are progress information only and must not be copied into IEEE paper tables.")
    $report.Add("")
    $report.Add("## Runs")
    $report.Add("")
    $report.Add("| Run | Status | Epochs | Last Epoch | Last mAP50 | Last mAP50-95 | Args | Best |")
    $report.Add("| --- | --- | ---: | ---: | ---: | ---: | --- | --- |")
    foreach ($row in $runRows) {
        $report.Add(
            "| " + $row.Run +
            " | " + $row.Status +
            " | " + $row.Epochs +
            " | " + $row.LastEpoch +
            " | " + $row.LastMap50 +
            " | " + $row.LastMap5095 +
            " | ``" + $row.Args + "``" +
            " | ``" + $row.Best + "`` |"
        )
    }
    $report.Add("")
    $report.Add("## Scale Outputs")
    $report.Add("")
    $report.Add("| Item | Status | Path | Detail |")
    $report.Add("| --- | --- | --- | --- |")
    foreach ($row in $scaleRows) {
        $report.Add("| " + $row.Item + " | " + $row.Status + " | ``" + $row.Path + "`` | " + $row.Detail + " |")
    }
    $report.Add("")
    $report.Add("## Processes")
    $report.Add("")
    $report.Add("| State |")
    $report.Add("| --- |")
    foreach ($row in $procRows) {
        $report.Add("| ``" + $row.State + "`` |")
    }
    $report.Add("")

    $report | Set-Content -Path $outputFullPath -Encoding UTF8
    Write-Host ""
    Write-Host "Wrote status snapshot: $outputFullPath"
}

if (![string]::IsNullOrWhiteSpace($HistoryPath)) {
    $historyFullPath = Join-Path (Resolve-Path (Join-Path $PSScriptRoot "..")) $HistoryPath
    $historyDir = Split-Path $historyFullPath -Parent
    New-Item -ItemType Directory -Force -Path $historyDir | Out-Null

    $processState = ($procRows | Select-Object -ExpandProperty State) -join " ; "
    $historyRows = foreach ($row in $runRows) {
        [pscustomobject]@{
            timestamp = $timestamp
            remote_root = $remoteRootValue
            completion_gate_epochs = $minEpochsValue
            run = $row.Run
            status = $row.Status
            epochs = $row.Epochs
            last_epoch = $row.LastEpoch
            last_map50 = $row.LastMap50
            last_map50_95 = $row.LastMap5095
            args = $row.Args
            best = $row.Best
            processes = $processState
        }
    }
    if (Test-Path -LiteralPath $historyFullPath) {
        $historyRows | Export-Csv -Path $historyFullPath -NoTypeInformation -Encoding UTF8 -Append
    }
    else {
        $historyRows | Export-Csv -Path $historyFullPath -NoTypeInformation -Encoding UTF8
    }
    Write-Host "Appended status history: $historyFullPath"
}
