from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = ROOT / "paper/text_hygiene_audit.md"


CHECKED_FILES = [
    "README.md",
    "paper/README.md",
    "paper/submission_checklist.md",
    "paper/evidence_audit.md",
    "paper/commands.md",
    "paper/CEA_FINAL_SUBMISSION_EXECUTION_PLAN.md",
    "paper/CEA_RESULT_INTEGRATION_PROTOCOL.md",
    "paper/CEA_RESULT_INTERPRETATION_MATRIX.md",
    "paper/CEA_SECTION_EVIDENCE_MAP.md",
    "paper/reference_verification_matrix.md",
    "paper/manuscript_submission_candidate.tex",
    "paper/manuscript_journal_gap_audit.md",
    "paper/tex_reference_audit.md",
    "paper/submission_audit_dashboard.md",
    "paper/pdf_text_readability_audit.md",
]


PATTERNS = [
    ("replacement character", re.compile("\ufffd")),
    ("soft hyphen", re.compile("\u00ad")),
    ("noncharacter U+FFFE", re.compile("\ufffe")),
    ("common mojibake token: U+9286", re.compile("\u9286")),
    ("common mojibake token: U+9428", re.compile("\u9428")),
    ("common mojibake token: U+9429", re.compile("\u9429")),
    ("common mojibake token: U+93C8", re.compile("\u93c8")),
    ("common mojibake token: U+59AB", re.compile("\u59ab")),
]


@dataclass
class HygieneCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_symbol(status: str) -> str:
    return {
        "ready": "READY",
        "missing": "MISSING",
    }[status]


def scan_file(rel_path: str) -> HygieneCheck:
    path = ROOT / rel_path
    if not path.exists():
        return HygieneCheck(
            rel_path,
            "missing",
            "file not found",
            "Restore the expected reader-facing text file.",
        )

    text = path.read_text(encoding="utf-8-sig")
    hits: list[str] = []
    for label, pattern in PATTERNS:
        matches = list(pattern.finditer(text))
        if matches:
            line_numbers = sorted({text.count("\n", 0, m.start()) + 1 for m in matches})
            shown = ", ".join(str(n) for n in line_numbers[:5])
            if len(line_numbers) > 5:
                shown += ", ..."
            hits.append(f"{label} at line {shown}")

    if hits:
        return HygieneCheck(
            rel_path,
            "missing",
            "; ".join(hits),
            "Remove hidden characters or mojibake from this reader-facing file.",
        )
    return HygieneCheck(rel_path, "ready", "no hygiene issues found")


def audit() -> list[HygieneCheck]:
    return [scan_file(rel_path) for rel_path in CHECKED_FILES]


def write_report(checks: list[HygieneCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# Text Hygiene Audit",
        "",
        "This report is generated by `tools/check_text_hygiene.py`. It scans reader-facing paper materials for hidden characters and common mojibake fragments. It does not inspect binary PDF contents.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| File | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for c in checks:
        lines.append(f"| `{c.item}` | {status_symbol(c.status)} | {c.evidence} | {c.action} |")

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the checked text file does not contain the configured hidden-character or mojibake patterns.",
            "- `MISSING` means the file is absent or contains text hygiene issues that should be fixed before submission.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
