from __future__ import annotations

import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BIB_PATH = ROOT / "paper/ieee_trans/references_seed.bib"
REPORT_PATH = ROOT / "paper/ieee_reference_audit.md"


ENTRY_RE = re.compile(r"@(?P<type>\w+)\s*\{\s*(?P<key>[^,\s]+)\s*,", re.M)
FIELD_RE = re.compile(r"^\s*(?P<field>\w+)\s*=", re.M)


@dataclass
class ReferenceCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_label(status: str) -> str:
    return {
        "ready": "READY",
        "pending": "PENDING",
        "missing": "MISSING",
    }[status]


def read_bib() -> str:
    if not BIB_PATH.exists():
        return ""
    return BIB_PATH.read_text(encoding="utf-8", errors="ignore")


def audit() -> list[ReferenceCheck]:
    text = read_bib()
    if not text:
        return [
            ReferenceCheck(
                "Seed bibliography exists",
                "missing",
                str(BIB_PATH.relative_to(ROOT)),
                "Create paper/ieee_trans/references_seed.bib.",
            )
        ]

    entries = list(ENTRY_RE.finditer(text))
    keys = [entry.group("key") for entry in entries]
    types = Counter(entry.group("type").lower() for entry in entries)
    duplicates = sorted(key for key, count in Counter(keys).items() if count > 1)
    fields = set(FIELD_RE.findall(text))

    checks = [
        ReferenceCheck(
            "Seed bibliography exists",
            "ready",
            str(BIB_PATH.relative_to(ROOT)),
        ),
        ReferenceCheck(
            "Reference entry count",
            "ready" if len(entries) >= 10 else "pending",
            f"{len(entries)} entries; types={dict(types)}",
            "" if len(entries) >= 10 else "Add core dataset, feature-fusion, attention, and tiny-object references.",
        ),
        ReferenceCheck(
            "Duplicate BibTeX keys",
            "ready" if not duplicates else "missing",
            "none" if not duplicates else ", ".join(duplicates),
            "" if not duplicates else "Rename duplicate keys.",
        ),
        ReferenceCheck(
            "Common fields present",
            "ready" if {"author", "title", "year"} <= fields else "missing",
            ", ".join(sorted(fields)),
            "" if {"author", "title", "year"} <= fields else "Review seed BibTeX fields.",
        ),
    ]
    return checks


def write_report(checks: list[ReferenceCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    pending = sum(1 for c in checks if c.status == "pending")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# IEEE Reference Audit",
        "",
        "This report is generated by `tools/check_ieee_references.py`. It performs lightweight checks on `paper/ieee_trans/references_seed.bib`.",
        "",
        "It does not certify final bibliographic correctness. Publisher metadata should be verified again before the final IEEE manuscript is compiled.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Pending: {pending}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for check in checks:
        lines.append(
            f"| {check.item} | {status_label(check.status)} | `{check.evidence}` | {check.action} |"
        )
    lines.append("")
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
