from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
README_PATH = ROOT / "README.md"
REPORT_PATH = ROOT / "paper/project_readme_presentation_audit.md"


@dataclass
class ReadmeCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_symbol(status: str) -> str:
    return {
        "ready": "READY",
        "missing": "MISSING",
    }[status]


def contains(text: str, pattern: str) -> bool:
    return re.search(pattern, text, flags=re.IGNORECASE | re.MULTILINE) is not None


def audit() -> list[ReadmeCheck]:
    if not README_PATH.exists():
        return [
            ReadmeCheck(
                "README exists",
                "missing",
                "README.md not found",
                "Restore the project-level README.",
            )
        ]

    text = README_PATH.read_text(encoding="utf-8")
    checks: list[ReadmeCheck] = [
        ReadmeCheck("README exists", "ready", "README.md"),
    ]

    required_sections = [
        ("Project title", r"^# .+VisDrone.+", "title:visdrone", "Add a clear project title."),
        ("Method section", r"^## 方法思路", "section:method", "Keep a method overview section."),
        ("Project structure", r"^## 项目结构", "section:structure", "Keep a repository structure section."),
        ("Environment setup", r"^## 环境安装", "section:setup", "Keep an installation section."),
        ("Dataset preparation", r"^## 数据集准备", "section:dataset", "Keep a dataset preparation section."),
        ("Training and validation", r"^## 训练与验证", "section:train-val", "Keep training and validation commands."),
        ("Inference and web demo", r"^## 推理与 Web 演示", "section:inference-demo", "Keep inference and demo commands."),
        ("Experiment results", r"^## 实验结果", "section:results", "Keep a concise result overview."),
        ("Paper materials", r"^## 论文材料", "section:paper-materials", "Keep a paper-material navigation section."),
        ("Reproducibility note", r"^## 结果可复现说明", "section:reproducibility", "Keep reproducibility and evidence notes."),
    ]
    for item, pattern, evidence, action in required_sections:
        found = contains(text, pattern)
        checks.append(
            ReadmeCheck(
                item,
                "ready" if found else "missing",
                evidence if found else "not found",
                "" if found else action,
            )
        )

    required_tokens = [
        ("Task and dataset", "VisDrone2019-DET"),
        ("Baseline family", "YOLO11n"),
        ("P2 branch", "P2"),
        ("Attention module", "CoordAttention"),
        ("Current paper PDF", "paper/manuscript_submission_candidate.pdf"),
        ("Submission package checklist", "paper/CEA_SUBMISSION_PACKAGE_CHECKLIST.md"),
        ("Audit dashboard", "paper/submission_audit_dashboard.md"),
        ("Evidence audit", "paper/evidence_audit.md"),
        ("Reproducibility commands", "paper/commands.md"),
    ]
    for item, token in required_tokens:
        found = token in text
        checks.append(
            ReadmeCheck(
                item,
                "ready" if found else "missing",
                token if found else "not found",
                "" if found else f"Add `{token}` to the project README.",
            )
        )

    forbidden_patterns = [
        ("Placeholder marker", r"待补充|TODO"),
        ("Progress-report phrasing", r"还没完成|尚未完成|等待.*跑完|明天再"),
        ("Unsupported certainty", r"100%.*中刊|保证.*录用|必.*录用"),
    ]
    for item, pattern in forbidden_patterns:
        found = contains(text, pattern)
        checks.append(
            ReadmeCheck(
                item,
                "missing" if found else "ready",
                "found forbidden pattern" if found else "not found",
                "Remove progress-report or unsupported-certainty wording from README.md." if found else "",
            )
        )

    return checks


def write_report(checks: list[ReadmeCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# Project README Presentation Audit",
        "",
        "This report is generated by `tools/check_project_readme_presentation.py`. It checks whether the repository-level README reads like a project introduction for advisors or reviewers, rather than an internal progress report.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for check in checks:
        lines.append(
            f"| {check.item} | {status_symbol(check.status)} | `{check.evidence}` | {check.action} |"
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the README contains the expected project-facing section/token or avoids the checked wording risk.",
            "- `MISSING` means the README should be revised before sharing the GitHub repository as a project introduction.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
