from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TARGETS_PATH = ROOT / "paper/tables/ieee_scale_eval_targets.csv"
FULL_OUTPUT_PATH = ROOT / "paper/tables/ieee_scale_results_visdrone.csv"
FULL_FIGURE_PATH = ROOT / "paper/figures/scale_analysis/ieee_scale_recall_visdrone.png"
LEGACY_OUTPUT_PATH = ROOT / "paper/tables/scale_group_results.csv"
REPORT_PATH = ROOT / "paper/ieee_scale_output_audit.md"

REQUIRED_SCALES = {"small", "medium", "large"}


@dataclass
class ScaleCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_label(status: str) -> str:
    return {
        "ready": "READY",
        "pending": "PENDING",
        "missing": "MISSING",
    }[status]


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def enabled_targets() -> list[str]:
    rows = read_csv(TARGETS_PATH)
    targets: list[str] = []
    for row in rows:
        enabled = row.get("enabled", "true").strip().lower()
        if enabled in {"0", "false", "no", "n"}:
            continue
        targets.append(row.get("model", "").strip())
    return [target for target in targets if target]


def audit() -> list[ScaleCheck]:
    checks: list[ScaleCheck] = []

    targets = enabled_targets()
    checks.append(
        ScaleCheck(
            "Scale target list",
            "ready" if targets else "missing",
            f"{len(targets)} enabled targets in {TARGETS_PATH.relative_to(ROOT)}",
            "" if targets else "Restore paper/tables/ieee_scale_eval_targets.csv.",
        )
    )

    legacy_rows = read_csv(LEGACY_OUTPUT_PATH)
    checks.append(
        ScaleCheck(
            "Legacy preliminary scale output",
            "ready" if legacy_rows else "pending",
            f"{len(legacy_rows)} rows in {LEGACY_OUTPUT_PATH.relative_to(ROOT)}",
            "" if legacy_rows else "Optional: run preliminary scale evaluation.",
        )
    )

    full_rows = read_csv(FULL_OUTPUT_PATH)
    if not full_rows:
        checks.append(
            ScaleCheck(
                "Full IEEE scale output",
                "pending",
                str(FULL_OUTPUT_PATH.relative_to(ROOT)),
                "Run tools/evaluate_scale_groups.py with paper/tables/ieee_scale_eval_targets.csv.",
            )
        )
    else:
        checks.append(
            ScaleCheck(
                "Full IEEE scale output",
                "ready",
                f"{len(full_rows)} rows in {FULL_OUTPUT_PATH.relative_to(ROOT)}",
            )
        )

        models_in_output = {row.get("model", "").strip() for row in full_rows}
        missing_models = sorted(set(targets) - models_in_output)
        checks.append(
            ScaleCheck(
                "Enabled targets covered",
                "ready" if not missing_models else "missing",
                "all enabled targets present" if not missing_models else ", ".join(missing_models),
                "" if not missing_models else "Re-run full scale evaluation after confirming weights.",
            )
        )

        scale_gaps: list[str] = []
        for target in targets:
            scales = {row.get("scale", "").strip() for row in full_rows if row.get("model", "").strip() == target}
            missing_scales = REQUIRED_SCALES - scales
            if missing_scales:
                scale_gaps.append(f"{target}: {','.join(sorted(missing_scales))}")
        checks.append(
            ScaleCheck(
                "Required scales covered",
                "ready" if not scale_gaps else "missing",
                "small/medium/large present for every enabled target" if not scale_gaps else "; ".join(scale_gaps),
                "" if not scale_gaps else "Re-run or inspect scale output.",
            )
        )

    checks.append(
        ScaleCheck(
            "Full IEEE scale figure",
            "ready" if FULL_FIGURE_PATH.exists() else "pending",
            str(FULL_FIGURE_PATH.relative_to(ROOT)),
            "" if FULL_FIGURE_PATH.exists() else "Generate figure with --plot-output.",
        )
    )

    return checks


def write_report(checks: list[ScaleCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    pending = sum(1 for c in checks if c.status == "pending")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# IEEE Scale Output Audit",
        "",
        "This report is generated by `tools/check_ieee_scale_outputs.py`. It checks whether scale-wise outputs are complete enough for IEEE small-object claims.",
        "",
        "The existing legacy `scale_group_results.csv` is preliminary. The full IEEE evidence gate is `paper/tables/ieee_scale_results_visdrone.csv` plus the corresponding figure.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Pending: {pending}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for check in checks:
        lines.append(
            f"| {check.item} | {status_label(check.status)} | `{check.evidence}` | {check.action} |"
        )

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the checked scale artifact exists and satisfies the configured coverage rule.",
            "- `PENDING` means the artifact is expected later and must not support final IEEE claims yet.",
            "- `MISSING` means a generated artifact exists but fails an expected coverage rule.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
