from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PAPER_DIR = ROOT / "paper"
TEX_PATH = PAPER_DIR / "manuscript_submission_candidate.tex"
PDF_PATH = PAPER_DIR / "manuscript_submission_candidate.pdf"
REPORT_PATH = PAPER_DIR / "tex_figure_audit.md"


@dataclass
class FigureCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_symbol(status: str) -> str:
    return {
        "ready": "READY",
        "partial": "PARTIAL",
        "missing": "MISSING",
    }[status]


def extract_includegraphics(text: str) -> list[str]:
    return [m.group(1).strip() for m in re.finditer(r"\\includegraphics(?:\[[^\]]*\])?\{([^}]+)\}", text)]


def count(pattern: str, text: str) -> int:
    return len(re.findall(pattern, text, flags=re.MULTILINE))


def audit() -> list[FigureCheck]:
    if not TEX_PATH.exists():
        return [
            FigureCheck(
                "LaTeX source exists",
                "missing",
                str(TEX_PATH.relative_to(ROOT)),
                "Restore or regenerate the LaTeX manuscript source.",
            )
        ]

    text = TEX_PATH.read_text(encoding="utf-8")
    figure_paths = extract_includegraphics(text)
    missing_figures = [p for p in figure_paths if not (PAPER_DIR / p).exists()]
    figure_env_count = count(r"\\begin\{figure\}", text)
    figure_label_count = count(r"\\label\{fig:", text)
    include_count = len(figure_paths)
    has_float_barrier = "\\FloatBarrier" in text and "\\section{结论}" in text and text.find("\\FloatBarrier") < text.find("\\section{结论}")

    checks = [
        FigureCheck(
            "Figure include paths",
            "ready" if figure_paths and not missing_figures else "missing",
            f"{include_count} includegraphics paths; missing: {', '.join(missing_figures) if missing_figures else 'none'}",
            "Restore missing figure files or update includegraphics paths." if missing_figures else "",
        ),
        FigureCheck(
            "Figure environments",
            "ready" if figure_env_count >= include_count else "partial",
            f"{figure_env_count} figure environments for {include_count} image includes",
            "Wrap image includes in figure environments when appropriate." if figure_env_count < include_count else "",
        ),
        FigureCheck(
            "Figure labels",
            "ready" if figure_label_count >= include_count else "partial",
            f"{figure_label_count} figure labels for {include_count} image includes",
            "Add labels for referenced figures." if figure_label_count < include_count else "",
        ),
        FigureCheck(
            "Float barrier before conclusion",
            "ready" if has_float_barrier else "missing",
            "FloatBarrier appears before conclusion" if has_float_barrier else "FloatBarrier missing or after conclusion",
            "Place \\FloatBarrier before \\section{结论}." if not has_float_barrier else "",
        ),
        FigureCheck(
            "Compiled PDF exists",
            "ready" if PDF_PATH.exists() else "missing",
            str(PDF_PATH.relative_to(ROOT)),
            "Build the PDF with tools/build_paper_pdf.ps1." if not PDF_PATH.exists() else "",
        ),
        FigureCheck(
            "PDF freshness",
            "ready" if PDF_PATH.exists() and PDF_PATH.stat().st_mtime >= TEX_PATH.stat().st_mtime else "partial",
            "PDF is not older than LaTeX source" if PDF_PATH.exists() and PDF_PATH.stat().st_mtime >= TEX_PATH.stat().st_mtime else "PDF is older than LaTeX source",
            "Rebuild the PDF." if not (PDF_PATH.exists() and PDF_PATH.stat().st_mtime >= TEX_PATH.stat().st_mtime) else "",
        ),
    ]
    return checks


def write_report(checks: list[FigureCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    partial = sum(1 for c in checks if c.status == "partial")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# LaTeX Figure Audit",
        "",
        "This report is generated by `tools/check_tex_figures.py`. It checks that figure files referenced by the current LaTeX candidate exist and that key float-layout safeguards are present.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Partial: {partial}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for c in checks:
        lines.append(f"| {c.item} | {status_symbol(c.status)} | `{c.evidence}` | {c.action} |")
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the current LaTeX figure reference or layout safeguard is present.",
            "- `PARTIAL` means the manuscript can compile but the figure structure should be improved.",
            "- `MISSING` means a figure file or float-layout safeguard is absent.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
