from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = ROOT / "paper/config_inventory_audit.md"


REQUIRED_FILES = [
    ("Dataset config", "configs/dataset/visdrone.yaml"),
    ("Project config", "configs/project.yaml"),
    ("P2 model config", "configs/models/yolo11n_p2.yaml"),
    ("P2 CoordAttention model config", "configs/models/yolo11n_p2_coordatt.yaml"),
    ("YOLO11n baseline train config", "configs/train/baseline_yolo11n.yaml"),
    ("YOLO11n 960 train config", "configs/train/baseline_yolo11n_960.yaml"),
    ("YOLO11s baseline train config", "configs/train/baseline_yolo11s.yaml"),
    ("YOLO11s 960 train config", "configs/train/baseline_yolo11s_960.yaml"),
    ("YOLOv8n baseline train config", "configs/train/baseline_yolov8n.yaml"),
    ("YOLOv8n 960 train config", "configs/train/baseline_yolov8n_960.yaml"),
    ("YOLOv5n train config", "configs/train/baseline_yolov5n.yaml"),
    ("YOLO11n-P2 train config", "configs/train/yolo11n_p2.yaml"),
    ("YOLO11n-P2 960 train config", "configs/train/yolo11n_p2_960.yaml"),
    ("YOLO11n-P2-CA train config", "configs/train/yolo11n_p2_coordatt.yaml"),
    ("YOLO11n-P2-CA 960 train config", "configs/train/yolo11n_p2_coordatt_960.yaml"),
    ("SmallObjAug train config", "configs/train/yolo11n_p2_coordatt_smallobj_aug.yaml"),
    ("Training script", "tools/train_baseline.py"),
    ("Validation script", "tools/val.py"),
    ("Speed benchmark script", "tools/benchmark_speed.py"),
    ("Paper table exporter", "tools/export_paper_tables.py"),
    ("Server queue script", "tools/run_cea_server_queue.sh"),
    ("Server status checker", "tools/check_cea_server_status.ps1"),
    ("Guarded server sync", "tools/sync_cea_server_results.ps1"),
]


@dataclass
class ConfigCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_symbol(status: str) -> str:
    return {
        "ready": "READY",
        "missing": "MISSING",
    }[status]


def audit() -> list[ConfigCheck]:
    checks: list[ConfigCheck] = []
    for item, rel_path in REQUIRED_FILES:
        path = ROOT / rel_path
        checks.append(
            ConfigCheck(
                item,
                "ready" if path.exists() else "missing",
                rel_path,
                "" if path.exists() else f"Restore or create {rel_path}.",
            )
        )
    return checks


def write_report(checks: list[ConfigCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# Config Inventory Audit",
        "",
        "This report is generated by `tools/check_config_inventory.py`. It verifies that the dataset, model, training, server-experiment, and paper-export configuration files needed by the manuscript track exist in the repository.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for c in checks:
        lines.append(f"| {c.item} | {status_symbol(c.status)} | `{c.evidence}` | {c.action} |")
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the configuration or script exists locally.",
            "- `MISSING` means the manuscript or reproducibility workflow references a file that should be restored.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
