from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "paper/ieee_trans/figure_source_manifest.md"
REPORT_PATH = ROOT / "paper/ieee_figure_audit.md"

PATH_RE = re.compile(r"`(?P<path>paper/figures/[^`]+)`")
FORBIDDEN_REFERENCES = [
    "paper/figures/pdf_review/",
    "runs/scale_group_smoke/",
]


@dataclass
class FigureCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_label(status: str) -> str:
    return {
        "ready": "READY",
        "pending": "PENDING",
        "missing": "MISSING",
    }[status]


def audit() -> list[FigureCheck]:
    checks: list[FigureCheck] = []
    if not MANIFEST_PATH.exists():
        return [
            FigureCheck(
                "Figure manifest exists",
                "missing",
                str(MANIFEST_PATH.relative_to(ROOT)),
                "Create paper/ieee_trans/figure_source_manifest.md.",
            )
        ]

    text = MANIFEST_PATH.read_text(encoding="utf-8", errors="ignore")
    checks.append(
        FigureCheck(
            "Figure manifest exists",
            "ready",
            str(MANIFEST_PATH.relative_to(ROOT)),
        )
    )

    ready_text = text.split("## Pending or Locked Figures", 1)[0]
    paths = sorted(set(match.group("path") for match in PATH_RE.finditer(ready_text)))
    if not paths:
        checks.append(
            FigureCheck(
                "Referenced figure paths",
                "missing",
                "none",
                "Add local figure paths in backticks to the manifest.",
            )
        )
    for rel_path in paths:
        path = ROOT / rel_path
        checks.append(
            FigureCheck(
                f"Figure exists: {rel_path}",
                "ready" if path.exists() else "missing",
                rel_path,
                "" if path.exists() else "Restore or regenerate this figure before use.",
            )
        )

    forbidden_hits = [ref for ref in FORBIDDEN_REFERENCES if ref in ready_text]
    checks.append(
        FigureCheck(
            "Forbidden figure-source references",
            "ready" if not forbidden_hits else "missing",
            "none" if not forbidden_hits else ", ".join(forbidden_hits),
            "" if not forbidden_hits else "Remove non-manuscript figure sources from ready candidates.",
        )
    )

    return checks


def write_report(checks: list[FigureCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    pending = sum(1 for c in checks if c.status == "pending")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# IEEE Figure Audit",
        "",
        "This report is generated by `tools/check_ieee_figures.py`. It checks the IEEE figure manifest for local figure existence and obvious non-manuscript sources.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Pending: {pending}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for check in checks:
        lines.append(
            f"| {check.item} | {status_label(check.status)} | `{check.evidence}` | {check.action} |"
        )
    lines.append("")
    REPORT_PATH.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
