from __future__ import annotations

import csv
import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PAPER_DIR = ROOT / "paper"
TEX_PATH = PAPER_DIR / "manuscript_submission_candidate.tex"
REPORT_PATH = PAPER_DIR / "tex_table_source_audit.md"


TABLE_SOURCES = {
    "tab:structure_diff": ("manual-structure", "Manually written architecture comparison; source configs are model YAML files."),
    "tab:env": ("manual-config", "Manually written experiment setting table from args/configs/logs."),
    "tab:main_results": ("paper/tables/main_comparison_for_paper.csv", "Main completed comparison rows."),
    "tab:external_baseline": ("paper/tables/main_comparison_for_paper.csv", "External baseline rows in completed comparison table."),
    "tab:ablation": ("paper/tables/ablation_results.csv", "Ablation results table."),
    "tab:scale_distribution": ("paper/tables/object_scale_distribution.csv", "Object scale distribution table."),
    "tab:scale_group_results": ("paper/tables/scale_group_results.csv", "Thresholded scale-group matching table."),
    "tab:per_class": ("paper/tables/per_class_results.csv", "Per-class validation results."),
    "tab:speed": ("paper/tables/speed_results.csv", "Speed benchmark results."),
    "tab:failure_reason": ("manual-analysis", "Qualitative failure taxonomy based on generated failure-case sheet."),
}


@dataclass
class TableCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_symbol(status: str) -> str:
    return {
        "ready": "READY",
        "partial": "PARTIAL",
        "missing": "MISSING",
    }[status]


def read_csv_rows(path: Path) -> int:
    if not path.exists():
        return 0
    with path.open(newline="", encoding="utf-8-sig") as f:
        return sum(1 for _ in csv.DictReader(f))


def extract_table_labels(text: str) -> list[str]:
    table_blocks = re.findall(r"\\begin\{table\}.*?\\end\{table\}", text, flags=re.DOTALL)
    labels: list[str] = []
    for block in table_blocks:
        match = re.search(r"\\label\{([^}]+)\}", block)
        labels.append(match.group(1).strip() if match else "<missing-label>")
    return labels


def audit() -> list[TableCheck]:
    if not TEX_PATH.exists():
        return [
            TableCheck(
                "LaTeX source exists",
                "missing",
                str(TEX_PATH.relative_to(ROOT)),
                "Restore or regenerate the LaTeX manuscript source.",
            )
        ]

    text = TEX_PATH.read_text(encoding="utf-8")
    labels = extract_table_labels(text)
    checks: list[TableCheck] = [
        TableCheck(
            "Table labels",
            "ready" if labels and "<missing-label>" not in labels else "missing",
            f"{len(labels)} table labels; missing labels: {labels.count('<missing-label>')}",
            "Add labels to all table environments." if "<missing-label>" in labels else "",
        )
    ]

    unknown = sorted(label for label in labels if label not in TABLE_SOURCES and label != "<missing-label>")
    checks.append(
        TableCheck(
            "Table source mapping",
            "ready" if not unknown else "missing",
            ", ".join(unknown) if unknown else "all table labels have source mapping",
            "Add table labels to TABLE_SOURCES with a CSV or manual provenance note." if unknown else "",
        )
    )

    for label in labels:
        if label == "<missing-label>" or label not in TABLE_SOURCES:
            continue
        source, note = TABLE_SOURCES[label]
        if source.startswith("paper/tables/"):
            source_path = ROOT / source
            rows = read_csv_rows(source_path)
            checks.append(
                TableCheck(
                    label,
                    "ready" if rows > 0 else "missing",
                    f"{source} ({rows} rows)",
                    "Regenerate or restore the CSV source." if rows == 0 else note,
                )
            )
        else:
            checks.append(
                TableCheck(
                    label,
                    "ready",
                    f"{source}: {note}",
                    "",
                )
            )

    return checks


def write_report(checks: list[TableCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    partial = sum(1 for c in checks if c.status == "partial")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# LaTeX Table Source Audit",
        "",
        "This report is generated by `tools/check_tex_table_sources.py`. It maps table labels in the current LaTeX candidate to CSV sources or explicit manual-provenance notes.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Partial: {partial}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action / Note |",
        "| --- | --- | --- | --- |",
    ]
    for c in checks:
        lines.append(f"| {c.item} | {status_symbol(c.status)} | `{c.evidence}` | {c.action} |")
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the table has a known CSV source or an explicit manual-provenance note.",
            "- `PARTIAL` means the table source exists but still needs manuscript-stage review.",
            "- `MISSING` means a table label, source mapping, or CSV source is absent.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
