from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAP_PATH = ROOT / "paper/CEA_SECTION_EVIDENCE_MAP.md"
REPORT_PATH = ROOT / "paper/section_evidence_map_audit.md"


REQUIRED_REFERENCES = [
    ("Section evidence map", "paper/CEA_SECTION_EVIDENCE_MAP.md"),
    ("Main comparison table", "paper/tables/main_comparison_for_paper.csv"),
    ("Speed table", "paper/tables/speed_results.csv"),
    ("Complexity table", "paper/tables/model_complexity.csv"),
    ("Object scale distribution", "paper/tables/object_scale_distribution.csv"),
    ("Reference verification matrix", "paper/reference_verification_matrix.md"),
    ("Reference draft", "paper/references.md"),
    ("Method overview figure", "paper/figures/method/hrpca_yolo11n_overview.png"),
    ("Ablation table", "paper/tables/ablation_results.csv"),
    ("Reproducibility commands", "paper/commands.md"),
    ("Configuration inventory audit", "paper/config_inventory_audit.md"),
    ("Reproducibility command audit", "paper/repro_commands_audit.md"),
    ("Scale-group table", "paper/tables/scale_group_results.csv"),
    ("Scale analysis figures", "paper/figures/scale_analysis"),
    ("Per-class table", "paper/tables/per_class_results.csv"),
    ("Qualitative figures", "paper/figures/qualitative"),
    ("Failure-case figures", "paper/figures/failure_cases"),
    ("Figure index", "paper/figure_index.md"),
]


FORBIDDEN_PATTERNS = [
    ("official test-dev AP claim", re.compile(r"官方\s*VisDrone\s*test-dev\s*AP")),
    ("universal superiority claim", re.compile(r"全面优于|显著优于主流|所有类别均提升|无额外计算成本")),
]

CONDITIONAL_OR_FORBIDDEN_CONTEXT = re.compile(
    r"不能|禁止|不使用|不提前|未完成|没有|只有在|条件|若|如果|禁用|写作边界"
)


@dataclass
class Check:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_symbol(status: str) -> str:
    return {
        "ready": "READY",
        "missing": "MISSING",
    }[status]


def exists(rel_path: str) -> bool:
    return (ROOT / rel_path).exists()


def audit_references() -> list[Check]:
    checks: list[Check] = []
    for item, rel_path in REQUIRED_REFERENCES:
        checks.append(
            Check(
                item,
                "ready" if exists(rel_path) else "missing",
                rel_path,
                "" if exists(rel_path) else f"Create or restore {rel_path}.",
            )
        )
    return checks


def audit_map_text() -> list[Check]:
    if not MAP_PATH.exists():
        return [
            Check(
                "Section evidence map text",
                "missing",
                str(MAP_PATH.relative_to(ROOT)),
                "Create paper/CEA_SECTION_EVIDENCE_MAP.md.",
            )
        ]

    text = MAP_PATH.read_text(encoding="utf-8-sig")
    checks = [
        Check(
            "Section evidence map has journal sections",
            "ready" if all(token in text for token in ["摘要", "引言", "方法", "实验", "结论"]) else "missing",
            str(MAP_PATH.relative_to(ROOT)),
            "" if all(token in text for token in ["摘要", "引言", "方法", "实验", "结论"]) else "Add the expected journal section coverage.",
        )
    ]
    for label, pattern in FORBIDDEN_PATTERNS:
        unsupported_lines = [
            line_no
            for line_no, line in enumerate(text.splitlines(), start=1)
            if pattern.search(line) and not CONDITIONAL_OR_FORBIDDEN_CONTEXT.search(line)
        ]
        found = bool(unsupported_lines)
        checks.append(
            Check(
                f"No unsupported claim: {label}",
                "missing" if found else "ready",
                f"line {unsupported_lines[0]}" if found else "not found outside conditional/forbidden context",
                "Rewrite the evidence map so unsupported claims are framed as forbidden or conditional.",
            )
        )
    return checks


def write_report(checks: list[Check]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# Section Evidence Map Audit",
        "",
        "This report is generated by `tools/check_section_evidence_map.py`. It checks whether the journal-manuscript section evidence map points to existing local evidence files and avoids unsupported final claims.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for check in checks:
        lines.append(f"| {check.item} | {status_symbol(check.status)} | `{check.evidence}` | {check.action} |")

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the referenced artifact exists or the checked claim is absent/conditional.",
            "- `MISSING` means the section evidence map references a missing artifact or contains an unsupported final-style claim.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit_references() + audit_map_text()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
