from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BRIEF_PATH = ROOT / "paper/advisor_progress_brief.md"
SNAPSHOT_PATH = ROOT / "paper/cea_server_status_snapshot.md"
REPORT_PATH = ROOT / "paper/advisor_progress_brief_audit.md"


REQUIRED_PHRASES = [
    "《计算机工程与应用》",
    "YOLO11n-P2-CoordAttention-960",
    "未完成 100 epoch",
    "不能进入论文结果表",
    "YOLO11n-960",
    "YOLO11n-P2-960",
    "YOLOv8n-960",
    "YOLO11s-960",
    "YOLOv5n-640",
    "不等同于官方 AP",
    "CEA_RESULT_INTERPRETATION_MATRIX.md",
]


@dataclass
class BriefCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_symbol(status: str) -> str:
    return {
        "ready": "READY",
        "missing": "MISSING",
    }[status]


def latest_server_epoch() -> str:
    if not SNAPSHOT_PATH.exists():
        return ""
    text = SNAPSHOT_PATH.read_text(encoding="utf-8")
    match = re.search(r"\| baseline_yolo11n_960_visdrone \| [A-Z]+ \| ([0-9]+) \|", text)
    return match.group(1) if match else ""


def audit() -> list[BriefCheck]:
    if not BRIEF_PATH.exists():
        return [
            BriefCheck(
                "Advisor brief exists",
                "missing",
                str(BRIEF_PATH.relative_to(ROOT)),
                "Run python tools/build_advisor_progress_brief.py.",
            )
        ]

    text = BRIEF_PATH.read_text(encoding="utf-8")
    checks = [
        BriefCheck("Advisor brief exists", "ready", str(BRIEF_PATH.relative_to(ROOT))),
        BriefCheck(
            "Generated-source marker",
            "ready" if "tools/build_advisor_progress_brief.py" in text else "missing",
            "builder script referenced" if "tools/build_advisor_progress_brief.py" in text else "builder script not referenced",
            "" if "tools/build_advisor_progress_brief.py" in text else "Regenerate the brief with the builder script.",
        ),
    ]

    for phrase in REQUIRED_PHRASES:
        checks.append(
            BriefCheck(
                f"Required phrase: {phrase}",
                "ready" if phrase in text else "missing",
                phrase if phrase in text else "not found",
                "" if phrase in text else "Regenerate or update the advisor brief.",
            )
        )

    epoch = latest_server_epoch()
    checks.append(
        BriefCheck(
            "Latest server epoch reflected",
            "ready" if epoch and f"{epoch}/100 epoch" in text else "missing",
            f"{epoch}/100 epoch" if epoch else "server epoch not found",
            "" if epoch and f"{epoch}/100 epoch" in text else "Regenerate the brief after checking server status.",
        )
    )

    stale_epoch_mentions = re.findall(r"([0-9]+)/100 epoch", text)
    checks.append(
        BriefCheck(
            "Single explicit server epoch",
            "ready" if len(stale_epoch_mentions) == 1 else "missing",
            f"{len(stale_epoch_mentions)} explicit epoch mentions",
            "" if len(stale_epoch_mentions) == 1 else "Keep only the current server progress line explicit.",
        )
    )

    return checks


def write_report(checks: list[BriefCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    missing = sum(1 for c in checks if c.status == "missing")
    lines = [
        "# Advisor Progress Brief Audit",
        "",
        "This report is generated by `tools/check_advisor_progress_brief.py`. It checks whether the advisor-facing progress brief contains the current server epoch, evidence boundaries, fair-comparison queue, and manuscript-rewrite gate. It does not validate experiment metrics.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for check in checks:
        lines.append(f"| {check.item} | {status_symbol(check.status)} | `{check.evidence}` | {check.action} |")
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the advisor brief contains the expected status or boundary statement.",
            "- `MISSING` means the brief is stale or incomplete and should be regenerated before sharing.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
