from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TRACKER_PATH = ROOT / "paper/CEA_OFFICIAL_REQUIREMENTS_TRACKER.md"
REPORT_PATH = ROOT / "paper/cea_official_requirements_tracker_audit.md"

REQUIRED_SOURCE_IDS = {"S1", "S2", "S3", "S4", "S5"}
REQUIRED_MANUAL_IDS = {"M1", "M2", "M3", "M4", "M5", "M6", "M7"}
REQUIRED_TOKENS = [
    "official-candidate",
    "cross-reference",
    "third-party",
    "not authoritative",
    "manually verified",
    "Online Check Log",
    "502-style",
    "Template file",
    "Upload file type",
    "Author metadata",
    "Declarations",
]


@dataclass
class TrackerCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_symbol(status: str) -> str:
    return {
        "ready": "READY",
        "missing": "MISSING",
    }[status]


def audit() -> list[TrackerCheck]:
    if not TRACKER_PATH.exists():
        return [
            TrackerCheck(
                "Official requirements tracker exists",
                "missing",
                str(TRACKER_PATH.relative_to(ROOT)),
                "Run python tools/build_cea_official_requirements_tracker.py.",
            )
        ]

    text = TRACKER_PATH.read_text(encoding="utf-8-sig")
    checks: list[TrackerCheck] = [
        TrackerCheck("Official requirements tracker exists", "ready", str(TRACKER_PATH.relative_to(ROOT))),
    ]

    missing_sources = sorted(source_id for source_id in REQUIRED_SOURCE_IDS if f"| {source_id} |" not in text)
    checks.append(
        TrackerCheck(
            "Required source IDs",
            "ready" if not missing_sources else "missing",
            "all S1-S5 present" if not missing_sources else ", ".join(missing_sources),
            "" if not missing_sources else "Add missing source candidate rows.",
        )
    )

    missing_manual = sorted(manual_id for manual_id in REQUIRED_MANUAL_IDS if f"| {manual_id} |" not in text)
    checks.append(
        TrackerCheck(
            "Required manual fields",
            "ready" if not missing_manual else "missing",
            "all M1-M7 present" if not missing_manual else ", ".join(missing_manual),
            "" if not missing_manual else "Add missing manual requirement fields.",
        )
    )

    missing_tokens = [token for token in REQUIRED_TOKENS if token not in text]
    checks.append(
        TrackerCheck(
            "Authority and caution wording",
            "ready" if not missing_tokens else "missing",
            "authority/caution tokens present" if not missing_tokens else ", ".join(missing_tokens),
            "" if not missing_tokens else "Add explicit source-authority and manual-verification wording.",
        )
    )

    pending_count = text.count("PENDING")
    checks.append(
        TrackerCheck(
            "Manual fields remain pending",
            "ready" if pending_count >= len(REQUIRED_MANUAL_IDS) else "missing",
            f"{pending_count} PENDING markers",
            "" if pending_count >= len(REQUIRED_MANUAL_IDS) else "Keep manual fields pending until final upload verification.",
        )
    )

    return checks


def write_report(checks: list[TrackerCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# CEA Official Requirements Tracker Audit",
        "",
        "This report is generated by `tools/check_cea_official_requirements_tracker.py`. It checks whether the official-requirements tracker records source candidates, manual verification fields, authority warnings, and pending markers for final upload checks.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for check in checks:
        lines.append(f"| {check.item} | {status_symbol(check.status)} | `{check.evidence}` | {check.action} |")

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the tracker has the expected source rows, manual fields, and caution wording.",
            "- `MISSING` means the tracker is missing a source, manual field, or authority boundary needed before final submission preparation.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
