from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
TEX_PATH = ROOT / "paper/manuscript_submission_candidate.tex"
REPORT_PATH = ROOT / "paper/tex_reference_audit.md"


@dataclass
class RefCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_symbol(status: str) -> str:
    return {
        "ready": "READY",
        "partial": "PARTIAL",
        "missing": "MISSING",
    }[status]


def extract_cite_keys(text: str) -> list[str]:
    keys: list[str] = []
    for match in re.finditer(r"\\cite\{([^}]+)\}", text):
        keys.extend(k.strip() for k in match.group(1).split(",") if k.strip())
    return keys


def extract_bibitem_keys(text: str) -> list[str]:
    return [m.group(1).strip() for m in re.finditer(r"\\bibitem\{([^}]+)\}", text)]


def audit() -> list[RefCheck]:
    if not TEX_PATH.exists():
        return [
            RefCheck(
                "LaTeX source exists",
                "missing",
                str(TEX_PATH.relative_to(ROOT)),
                "Restore or regenerate the LaTeX manuscript.",
            )
        ]

    text = TEX_PATH.read_text(encoding="utf-8")
    cite_keys = extract_cite_keys(text)
    bibitem_keys = extract_bibitem_keys(text)
    cite_set = set(cite_keys)
    bibitem_set = set(bibitem_keys)

    missing_bibitems = sorted(cite_set - bibitem_set)
    unused_bibitems = sorted(bibitem_set - cite_set)
    duplicate_bibitems = sorted({k for k in bibitem_keys if bibitem_keys.count(k) > 1})
    bad_chars = sorted(set(re.findall(r"[\u00ad\ufffe]", text)))

    cite_command_count = len(re.findall(r"\\cite\{", text))

    checks = [
        RefCheck(
            "Citation commands",
            "ready" if cite_keys else "missing",
            f"{len(cite_keys)} cite keys across {cite_command_count} cite commands",
            "" if cite_keys else "Add citations to related work and method sections.",
        ),
        RefCheck(
            "Bibliography entries",
            "ready" if bibitem_keys else "missing",
            f"{len(bibitem_keys)} bibitem entries",
            "" if bibitem_keys else "Add bibliography entries.",
        ),
        RefCheck(
            "Every cite has a bibitem",
            "ready" if not missing_bibitems else "missing",
            ", ".join(missing_bibitems) if missing_bibitems else "all cited keys have bibitems",
            "Add missing bibitem entries." if missing_bibitems else "",
        ),
        RefCheck(
            "Every bibitem is cited",
            "ready" if not unused_bibitems else "partial",
            ", ".join(unused_bibitems) if unused_bibitems else "all bibitems are cited",
            "Remove unused entries or cite them in the manuscript." if unused_bibitems else "",
        ),
        RefCheck(
            "Duplicate bibitem keys",
            "ready" if not duplicate_bibitems else "missing",
            ", ".join(duplicate_bibitems) if duplicate_bibitems else "none",
            "Rename or remove duplicate bibliography keys." if duplicate_bibitems else "",
        ),
        RefCheck(
            "Reference hidden characters",
            "ready" if not bad_chars else "missing",
            ", ".join(f"U+{ord(c):04X}" for c in bad_chars) if bad_chars else "none",
            "Remove hidden soft-hyphen or replacement characters." if bad_chars else "",
        ),
        RefCheck(
            "Reference breadth",
            "partial" if len(bibitem_keys) < 25 else "ready",
            f"{len(bibitem_keys)} entries; final target is 25-35 verified references",
            "Continue adding verified recent Chinese and international related work before final submission."
            if len(bibitem_keys) < 25
            else "",
        ),
    ]
    return checks


def write_report(checks: list[RefCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    partial = sum(1 for c in checks if c.status == "partial")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# LaTeX Reference Audit",
        "",
        "This report is generated by `tools/check_tex_references.py`. It checks citation/bibliography consistency in the current LaTeX candidate and does not verify the scholarly quality of each reference.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Partial: {partial}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for c in checks:
        lines.append(f"| {c.item} | {status_symbol(c.status)} | `{c.evidence}` | {c.action} |")

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the local LaTeX citation structure is internally consistent for this item.",
            "- `PARTIAL` means the structure is usable but still below final journal-submission expectations.",
            "- `MISSING` means the current LaTeX source has a citation or bibliography problem that should be fixed.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
