from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
COMMANDS_PATH = ROOT / "paper/commands.md"
REPORT_PATH = ROOT / "paper/repro_commands_audit.md"


REQUIRED_COMMANDS = [
    ("Export paper tables", r"python\s+tools/export_paper_tables\.py"),
    ("Speed benchmark", r"python\s+tools/benchmark_speed\.py"),
    ("Baseline YOLO11n training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/baseline_yolo11n\.yaml"),
    ("P2 training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/yolo11n_p2\.yaml"),
    ("P2 CoordAttention training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/yolo11n_p2_coordatt\.yaml"),
    ("P2 CoordAttention 960 training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/yolo11n_p2_coordatt_960\.yaml"),
    ("Small-object augmentation training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/yolo11n_p2_coordatt_smallobj_aug\.yaml"),
    ("YOLOv8n baseline training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/baseline_yolov8n\.yaml"),
    ("YOLO11s baseline training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/baseline_yolo11s\.yaml"),
    ("Server status checker", r"\.\\tools\\check_cea_server_status\.ps1"),
    ("Guarded server sync", r"\.\\tools\\sync_cea_server_results\.ps1"),
    ("Fair YOLO11n 960 training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/baseline_yolo11n_960\.yaml"),
    ("Fair P2 960 training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/yolo11n_p2_960\.yaml"),
    ("Fair YOLOv8n 960 training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/baseline_yolov8n_960\.yaml"),
    ("Fair YOLO11s 960 training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/baseline_yolo11s_960\.yaml"),
    ("YOLOv5n baseline training", r"python\s+tools/train_baseline\.py\s+--config\s+configs/train/baseline_yolov5n\.yaml"),
    ("Scale distribution analysis", r"python\s+tools/analyze_object_scales\.py"),
    ("Scale-group evaluation", r"python\s+tools/evaluate_scale_groups\.py"),
    ("VisDrone test-dev export", r"python\s+tools/export_visdrone_testdev\.py"),
    ("Paper PDF build", r"\.\\tools\\build_paper_pdf\.ps1"),
    ("Full paper audit runner", r"python\s+tools/run_paper_audits\.py"),
    ("Submission readiness audit", r"python\s+tools/audit_submission_readiness\.py"),
    ("Evidence audit builder", r"python\s+tools/build_evidence_audit\.py"),
    ("Text hygiene audit", r"python\s+tools/check_text_hygiene\.py"),
    ("Paper consistency audit", r"python\s+tools/check_paper_consistency\.py"),
    ("Per-class validation", r"python\s+tools/val\.py"),
]


@dataclass
class CommandCheck:
    item: str
    status: str
    evidence: str
    action: str = ""


def status_symbol(status: str) -> str:
    return {
        "ready": "READY",
        "missing": "MISSING",
    }[status]


def audit() -> list[CommandCheck]:
    if not COMMANDS_PATH.exists():
        return [
            CommandCheck(
                "Commands document exists",
                "missing",
                str(COMMANDS_PATH.relative_to(ROOT)),
                "Create paper/commands.md.",
            )
        ]

    text = COMMANDS_PATH.read_text(encoding="utf-8")
    checks = [
        CommandCheck(
            "Commands document exists",
            "ready",
            str(COMMANDS_PATH.relative_to(ROOT)),
            "",
        )
    ]
    for item, pattern in REQUIRED_COMMANDS:
        found = re.search(pattern, text, flags=re.MULTILINE) is not None
        checks.append(
            CommandCheck(
                item,
                "ready" if found else "missing",
                pattern if found else "not found",
                "" if found else "Add the reproducibility command to paper/commands.md.",
            )
        )
    return checks


def write_report(checks: list[CommandCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# Reproducibility Commands Audit",
        "",
        "This report is generated by `tools/check_repro_commands.py`. It checks whether `paper/commands.md` contains the command families needed to reproduce training, validation, paper tables, server synchronization, audits, and PDF generation.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| Item | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for c in checks:
        lines.append(f"| {c.item} | {status_symbol(c.status)} | `{c.evidence}` | {c.action} |")
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the command family is documented in `paper/commands.md`.",
            "- `MISSING` means the command should be added before final submission.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
