from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REPORT_PATH = ROOT / "paper/ieee_claim_audit.md"


FINAL_FACING_FILES = [
    "paper/ieee_trans/main.tex",
    "paper/ieee_trans/cover_letter_draft.md",
    "paper/ieee_trans/abstract.md",
    "README.md",
]


FORBIDDEN_PATTERNS = [
    ("unsupported SOTA claim", re.compile(r"\b(state[- ]of[- ]the[- ]art|SOTA)\b", re.I)),
    ("unsupported broad superiority", re.compile(r"\b(outperform(?:s|ed|ing)?|surpass(?:es|ed|ing)?|beats?)\b.*\b(all|larger|YOLO11s|state[- ]of[- ]the[- ]art|SOTA)\b", re.I)),
    ("unsupported generalization", re.compile(r"\b(generalize(?:s|d)?|generalization|robust across datasets)\b", re.I)),
    ("unsupported significance", re.compile(r"\b(significant(?:ly)?|consistent(?:ly)?)\b.*\b(improve(?:s|d|ment)?|gain(?:s)?)\b", re.I)),
    ("official test-dev result", re.compile(r"\b(test[- ]dev|test challenge|official benchmark)\b.*\b(result|AP|mAP|score)\b", re.I)),
    ("TOFC performance claim", re.compile(r"\bTOFC\b.*\b(improve(?:s|d|ment)?|outperform(?:s|ed)?|gain(?:s)?|boost(?:s|ed)?)\b", re.I)),
]


NEGATING_CONTEXT = re.compile(
    r"\b(do not|does not|cannot|must not|not yet|pending|locked|avoid|without evidence|before evidence)\b",
    re.I,
)


@dataclass
class ClaimCheck:
    file: str
    status: str
    evidence: str
    action: str = ""


def status_label(status: str) -> str:
    return {
        "ready": "READY",
        "pending": "PENDING",
        "missing": "MISSING",
    }[status]


def line_hits(text: str, pattern: re.Pattern[str]) -> list[int]:
    hits: list[int] = []
    for number, line in enumerate(text.splitlines(), start=1):
        if pattern.search(line) and not NEGATING_CONTEXT.search(line):
            hits.append(number)
    return hits


def check_file(rel_path: str) -> ClaimCheck:
    path = ROOT / rel_path
    if not path.exists():
        return ClaimCheck(
            rel_path,
            "pending",
            "file not present",
            "No action needed until this final-facing file is created.",
        )

    text = path.read_text(encoding="utf-8", errors="ignore")
    findings: list[str] = []
    for label, pattern in FORBIDDEN_PATTERNS:
        hits = line_hits(text, pattern)
        if hits:
            shown = ", ".join(str(n) for n in hits[:8])
            if len(hits) > 8:
                shown += ", ..."
            findings.append(f"{label} at line {shown}")

    if not findings:
        return ClaimCheck(rel_path, "ready", "no configured unsupported claim patterns found")

    return ClaimCheck(
        rel_path,
        "missing",
        "; ".join(findings),
        "Revise wording or add traceable evidence before sharing/submission.",
    )


def audit() -> list[ClaimCheck]:
    return [check_file(path) for path in FINAL_FACING_FILES]


def write_report(checks: list[ClaimCheck]) -> None:
    total = len(checks)
    ready = sum(1 for c in checks if c.status == "ready")
    pending = sum(1 for c in checks if c.status == "pending")
    missing = sum(1 for c in checks if c.status == "missing")

    lines = [
        "# IEEE Claim Audit",
        "",
        "This report is generated by `tools/check_ieee_claims.py`. It scans final-facing IEEE text for unsupported claims that are locked by `paper/ieee_claim_boundary.md`.",
        "",
        "Planning documents are intentionally excluded because they may contain examples of forbidden claims.",
        "",
        "## Summary",
        "",
        f"- Total checks: {total}",
        f"- Ready: {ready}",
        f"- Pending: {pending}",
        f"- Missing: {missing}",
        "",
        "## Checks",
        "",
        "| File | Status | Evidence | Action |",
        "| --- | --- | --- | --- |",
    ]
    for check in checks:
        lines.append(
            f"| {check.file} | {status_label(check.status)} | `{check.evidence}` | {check.action} |"
        )

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "- `READY` means the file exists and no configured unsupported claim pattern was found.",
            "- `PENDING` means the final-facing file does not exist yet.",
            "- `MISSING` means a final-facing text contains claim wording that needs revision or evidence.",
        ]
    )
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    checks = audit()
    write_report(checks)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
