from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "paper/ieee_trans/tables"

MAIN_RESULTS = ROOT / "paper/tables/main_comparison_for_paper.csv"
SPEED_RESULTS = ROOT / "paper/tables/speed_results.csv"
MODEL_COMPLEXITY = ROOT / "paper/tables/model_complexity.csv"
SCALE_RESULTS = ROOT / "paper/tables/ieee_scale_results_visdrone.csv"
SCALE_AP_RESULTS = ROOT / "paper/tables/ieee_scale_ap_results_visdrone.csv"
LITERATURE_CONTEXT = ROOT / "paper/tables/ieee_literature_context.csv"


MAIN_MODELS = [
    "YOLOv5n baseline",
    "YOLOv8n baseline",
    "YOLOv8n baseline 960",
    "YOLO11n baseline",
    "YOLO11n baseline 960",
    "YOLO11n-P2-960",
    "YOLO11n-P2-CoordAttention-960",
    "YOLO11n-P2-TOFC-960",
    "YOLO11s baseline 960",
]

SPEED_MODELS = [
    "YOLO11n baseline 960",
    "YOLO11n-P2-960",
    "YOLO11n-P2-CoordAttention-960",
    "YOLO11n-P2-TOFC-960",
    "YOLOv8n baseline 960",
    "YOLO11s baseline 960",
]

DISPLAY_NAMES = {
    "YOLOv8n baseline": "YOLOv8n",
    "YOLOv8n baseline 960": "YOLOv8n-960",
    "YOLOv5n baseline": "YOLOv5n",
    "YOLO11s baseline": "YOLO11s",
    "YOLO11s baseline 960": "YOLO11s-960",
    "YOLO11n baseline": "YOLO11n",
    "YOLO11n baseline 960": "YOLO11n-960",
    "YOLO11n-P2-CoordAttention": "YOLO11n-P2-CA",
    "YOLO11n-P2-CoordAttention-960": "YOLO11n-P2-CA-960",
    "YOLO11n-P2-CoordAttention-SmallObjAug": "YOLO11n-P2-CA-Aug",
    "YOLO11n-P2-TOFC-960": "YOLO11n-P2-TOFC-960",
}


def read_csv(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(newline="", encoding="utf-8-sig") as f:
        return list(csv.DictReader(f))


def fmt(value: str, digits: int = 3) -> str:
    try:
        return f"{float(value):.{digits}f}"
    except (TypeError, ValueError):
        return value


def params_m(value: str) -> str:
    try:
        return f"{float(value) / 1_000_000:.3f}"
    except (TypeError, ValueError):
        return value


def tex_escape(value: str) -> str:
    return (
        value.replace("\\", "\\textbackslash{}")
        .replace("_", "\\_")
        .replace("%", "\\%")
        .replace("&", "\\&")
        .replace("#", "\\#")
    )


def display_name(model: str) -> str:
    return DISPLAY_NAMES.get(model, model)


def table_env(caption: str, label: str, columns: str, header: str, rows: list[str], note: str = "") -> str:
    body = "\n".join(rows)
    lines = [
        "% Auto-generated by tools/export_ieee_tables.py.",
        "% Values are copied from audited CSV files; do not edit numbers by hand.",
        "\\begin{table}[t]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        "\\footnotesize",
        f"\\begin{{tabular}}{{{columns}}}",
        "\\hline",
        header + " \\\\",
        "\\hline",
        body,
        "\\hline",
        "\\end{tabular}",
    ]
    if note:
        lines.append(f"\\vspace{{1mm}}\\par\\footnotesize {note}")
    lines.append("\\end{table}")
    return "\n".join(lines) + "\n"


def export_main_results() -> None:
    rows = read_csv(MAIN_RESULTS)
    by_model = {row["model"]: row for row in rows}
    tex_rows: list[str] = []
    for model in MAIN_MODELS:
        row = by_model.get(model)
        if not row:
            continue
        tex_rows.append(
            " & ".join(
                [
                    tex_escape(display_name(model)),
                    row["input_size"],
                    params_m(row["params"]),
                    fmt(row["precision"]),
                    fmt(row["recall"]),
                    fmt(row["best_map50"]),
                    fmt(row["best_map50_95"]),
                ]
            )
            + " \\\\"
        )
    content = table_env(
        caption="Detection results on the VisDrone2019-DET validation set.",
        label="tab:ieee_visdrone_main_results",
        columns="lrrrrrr",
        header="Model & Img & Params/M & P & R & mAP50 & mAP50--95",
        rows=tex_rows,
        note="All values are traced to \\texttt{paper/tables/main\\_comparison\\_for\\_paper.csv}.",
    )
    (OUT_DIR / "visdrone_main_results.tex").write_text(content, encoding="utf-8")


def export_speed_complexity() -> None:
    speed_rows = {row["model"]: row for row in read_csv(SPEED_RESULTS)}
    complexity_rows = {row["model"]: row for row in read_csv(MODEL_COMPLEXITY)}
    tex_rows: list[str] = []
    for model in SPEED_MODELS:
        speed = speed_rows.get(model)
        complexity = complexity_rows.get(model)
        if not speed or not complexity:
            continue
        tex_rows.append(
            " & ".join(
                [
                    tex_escape(display_name(model)),
                    speed["imgsz"],
                    params_m(complexity["parameters"]),
                    fmt(complexity["gflops"], 1),
                    fmt(complexity["weight_size_mb"], 2),
                    fmt(speed["mean_latency_ms_wall"], 2),
                    fmt(speed["fps_wall"], 2),
                ]
            )
            + " \\\\"
        )
    content = table_env(
        caption="Speed and complexity comparison for completed VisDrone models.",
        label="tab:ieee_speed_complexity",
        columns="lrrrrrr",
        header="Model & Img & Params/M & GFLOPs & MB & Latency/ms & FPS",
        rows=tex_rows,
        note="Latency and FPS use the wall-clock protocol recorded in \\texttt{paper/tables/speed\\_results.csv}.",
    )
    (OUT_DIR / "speed_complexity.tex").write_text(content, encoding="utf-8")


def export_scale_results() -> None:
    rows = read_csv(SCALE_RESULTS)
    models: list[str] = []
    for row in rows:
        if row["model"] not in models:
            models.append(row["model"])
    lookup = {(row["model"], row["scale"]): row for row in rows}
    tex_rows: list[str] = []
    for model in models:
        values = [tex_escape(display_name(model))]
        for scale in ["small", "medium", "large"]:
            row = lookup.get((model, scale))
            values.extend([fmt(row["recall"]) if row else "--", fmt(row["precision"]) if row else "--"])
        tex_rows.append(" & ".join(values) + " \\\\")
    content = table_env(
        caption="Scale-wise recall and precision on the VisDrone2019-DET validation set.",
        label="tab:ieee_scale_recall_precision",
        columns="lrrrrrr",
        header="Model & S-R & S-P & M-R & M-P & L-R & L-P",
        rows=tex_rows,
        note="S/M/L denote small, medium, and large GT object groups. This table reports recall/precision, not AP.",
    )
    (OUT_DIR / "scale_recall_precision.tex").write_text(content, encoding="utf-8")


def export_scale_ap_results() -> None:
    rows = read_csv(SCALE_AP_RESULTS)
    if not rows:
        return
    models: list[str] = []
    for row in rows:
        if row["model"] not in models:
            models.append(row["model"])
    lookup = {(row["model"], row["scale"]): row for row in rows}
    tex_rows: list[str] = []
    for model in models:
        values = [tex_escape(display_name(model))]
        for scale in ["small", "medium", "large"]:
            row = lookup.get((model, scale))
            values.extend([fmt(row["ap50"]) if row else "--", fmt(row["map50_95"]) if row else "--"])
        tex_rows.append(" & ".join(values) + " \\\\")
    content = table_env(
        caption="Local scale-bin AP on the VisDrone2019-DET validation set.",
        label="tab:ieee_scale_bin_ap",
        columns="lrrrrrr",
        header="Model & S-AP50 & S-mAP & M-AP50 & M-mAP & L-AP50 & L-mAP",
        rows=tex_rows,
        note=(
            "S/M/L denote small, medium, and large object groups. "
            "This diagnostic uses local scale-bin filtering and is not an official COCO or VisDrone small-object AP metric."
        ),
    )
    (OUT_DIR / "scale_bin_ap.tex").write_text(content, encoding="utf-8")


def export_literature_context() -> None:
    rows = read_csv(LITERATURE_CONTEXT)
    if not rows:
        return
    tex_rows: list[str] = []
    for row in rows:
        tex_rows.append(
            " & ".join(
                [
                    tex_escape(row["work"]),
                    tex_escape(row["seed_key"]),
                    row["year"],
                    tex_escape(row["base_or_focus"]),
                    tex_escape(row["current_use"]),
                ]
            )
            + " \\\\"
        )
    content = table_env(
        caption="Literature context for recent UAV small-object YOLO methods.",
        label="tab:ieee_literature_context",
        columns="llrp{0.28\\linewidth}p{0.28\\linewidth}",
        header="Work & Key & Year & Focus & Use",
        rows=tex_rows,
        note=(
            "This table is for related-work context only. "
            "It does not contain reproduced performance values or a direct ranking."
        ),
    )
    (OUT_DIR / "literature_context.tex").write_text(content, encoding="utf-8")


def export_manifest() -> None:
    lines = [
        "# IEEE Table Source Manifest",
        "",
        "Generated by `tools/export_ieee_tables.py`.",
        "",
        "| Output | Source CSV | Claim Boundary |",
        "| --- | --- | --- |",
        "| `visdrone_main_results.tex` | `paper/tables/main_comparison_for_paper.csv` | Completed VisDrone validation results only |",
        "| `speed_complexity.tex` | `paper/tables/speed_results.csv`, `paper/tables/model_complexity.csv` | Completed local speed/complexity evidence only |",
        "| `scale_recall_precision.tex` | `paper/tables/ieee_scale_results_visdrone.csv` | Scale-wise recall/precision only; not AP-small |",
        "| `scale_bin_ap.tex` | `paper/tables/ieee_scale_ap_results_visdrone.csv` | Local scale-bin AP diagnostic; not official COCO/VisDrone AP-small |",
        "| `literature_context.tex` | `paper/tables/ieee_literature_context.csv` | Related-work context only; no reproduced performance ranking |",
        "",
        "Regenerate these files after any final-model, speed, or scale-wise result changes.",
    ]
    (OUT_DIR / "README.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    export_main_results()
    export_speed_complexity()
    export_scale_results()
    export_scale_ap_results()
    export_literature_context()
    export_manifest()
    print(f"Wrote IEEE tables to {OUT_DIR.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
