from __future__ import annotations

import hashlib
import zipfile
from dataclasses import dataclass
from pathlib import Path
import xml.etree.ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
TEMPLATE_DIR = ROOT / "paper/templates"
REPORT_PATH = ROOT / "paper/CEA_TEMPLATE_REQUIREMENTS_SUMMARY.md"
OFFICIAL_REQUIREMENTS_URL = "http://cea.ceaj.org/CN/column/column16.shtml"


@dataclass(frozen=True)
class TemplateInfo:
    path: Path
    size: int
    sha256: str
    modified: str
    paragraphs: list[str]


def find_template() -> Path | None:
    files = sorted(TEMPLATE_DIR.glob("*.docx"))
    return files[0] if files else None


def read_docx_paragraphs(path: Path) -> list[str]:
    ns = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}
    with zipfile.ZipFile(path) as archive:
        document = ET.fromstring(archive.read("word/document.xml"))

    paragraphs: list[str] = []
    for para in document.findall(".//w:p", ns):
        parts = [node.text for node in para.findall(".//w:t", ns) if node.text]
        text = "".join(parts).strip()
        if text:
            paragraphs.append(text)
    return paragraphs


def collect_template_info(path: Path) -> TemplateInfo:
    stat = path.stat()
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    modified = __import__("datetime").datetime.fromtimestamp(stat.st_mtime).strftime("%Y-%m-%d %H:%M:%S")
    return TemplateInfo(
        path=path,
        size=stat.st_size,
        sha256=digest,
        modified=modified,
        paragraphs=read_docx_paragraphs(path),
    )


def find_first(paragraphs: list[str], *keywords: str) -> str:
    for index, paragraph in enumerate(paragraphs, start=1):
        if all(keyword in paragraph for keyword in keywords):
            return f"P{index}"
    return "not found"


def write_report(info: TemplateInfo | None) -> None:
    if info is None:
        lines = [
            "# CEA Template Requirements Summary",
            "",
            "No official CEA `.docx` template was found under `paper/templates/`.",
            "",
            "## Summary",
            "",
            "- Template status: MISSING",
            "- Action: copy the current CEA template into `paper/templates/` and rerun this script.",
        ]
        REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return

    paragraphs = info.paragraphs
    evidence_rows = [
        ("Chinese title", find_first(paragraphs, "题名", "25")),
        ("Chinese abstract", find_first(paragraphs, "摘要", "300")),
        ("Chinese keywords", find_first(paragraphs, "关键词", "3～8")),
        ("English abstract", find_first(paragraphs, "Abstract")),
        ("Figures", find_first(paragraphs, "插图")),
        ("Tables", find_first(paragraphs, "表格")),
        ("References", find_first(paragraphs, "参考文献", "20")),
        ("Author contact", find_first(paragraphs, "联系人")),
    ]

    lines = [
        "# CEA Template Requirements Summary",
        "",
        "This file is generated by `tools/extract_cea_template_requirements.py` from the local CEA Word template. It summarizes formatting requirements used for manuscript migration; it does not rewrite the manuscript and does not add experiment results.",
        "",
        "## Template Evidence",
        "",
        "| Field | Value |",
        "| --- | --- |",
        f"| Official requirements page provided by user | `{OFFICIAL_REQUIREMENTS_URL}` |",
        f"| Local template | `{info.path.relative_to(ROOT).as_posix()}` |",
        f"| Size | {info.size} bytes |",
        f"| Last modified | {info.modified} |",
        f"| SHA256 | `{info.sha256}` |",
        f"| Extracted non-empty paragraphs | {len(info.paragraphs)} |",
        "",
        "## Extracted Requirement Summary",
        "",
        "| Area | Requirement summary | Evidence paragraph |",
        "| --- | --- | --- |",
        "| Title | Chinese title should be concise, generally within 25 Chinese characters; avoid unnecessary abbreviations and weak generic wording. | `{}` |".format(evidence_rows[0][1]),
        "| Abstract | Chinese abstract should be about 300 Chinese characters and cover problem/purpose, method, result, and conclusion; English abstract should correspond to the Chinese abstract. | `{}` / `{}` |".format(evidence_rows[1][1], evidence_rows[3][1]),
        "| Keywords | Provide 3-8 keywords separated by semicolons; English keywords should use lowercase except abbreviations. | `{}` |".format(evidence_rows[2][1]),
        "| Body layout | Main text should follow the journal template style, including two-column layout and journal-defined body font/spacing. | `P27` |",
        "| Figures | Figures need figure numbers, Chinese and English captions, subfigure captions when applicable, editable vector files for drawn diagrams, and sufficiently clear raster images. | `{}` |".format(evidence_rows[4][1]),
        "| Tables | Tables need table numbers, Chinese and English captions, three-line table style, units where needed, and must not be inserted as images. | `{}` |".format(evidence_rows[5][1]),
        "| References | Use sequential numeric citation style; references should be formal publications where possible, with 20 or more references recommended; Chinese references need original English information. | `{}` |".format(evidence_rows[6][1]),
        "| Contact details | Contact person, postal address, email, and phone should be provided after the references or in the required submission metadata. | `{}` |".format(evidence_rows[7][1]),
        "",
        "## Migration Impact",
        "",
        "- The current LaTeX candidate is not yet in the official Word-template layout.",
        "- Before formal upload, migrate title, authors, affiliations, abstracts, keywords, figures, tables, references, funding, acknowledgements, declarations, and contact details into the CEA template or the format required by the submission system.",
        "- Preserve all experiment numbers from `paper/tables/`; do not manually recompute metrics during template migration.",
        "- If the official submission system requires Word, use this local template as the base document for the final manuscript file.",
    ]
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    template = find_template()
    info = collect_template_info(template) if template else None
    write_report(info)
    print(f"Wrote {REPORT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
