from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

import fitz
from PIL import Image, ImageDraw


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_PDF = ROOT / "paper/manuscript_submission_candidate.pdf"
DEFAULT_OUTPUT = ROOT / "paper/figures/pdf_review/manuscript_pages_contact_sheet.jpg"
DEFAULT_REPORT = ROOT / "paper/pdf_visual_contact_sheet.md"


@dataclass(frozen=True)
class RenderedPage:
    page_no: int
    image: Image.Image


def file_size(path: Path) -> str:
    size = path.stat().st_size
    if size >= 1024 * 1024:
        return f"{size / (1024 * 1024):.2f} MB"
    if size >= 1024:
        return f"{size / 1024:.1f} KB"
    return f"{size} B"


def render_pages(pdf_path: Path, zoom: float) -> list[RenderedPage]:
    pages: list[RenderedPage] = []
    doc = fitz.open(pdf_path)
    matrix = fitz.Matrix(zoom, zoom)
    for index, page in enumerate(doc, start=1):
        pix = page.get_pixmap(matrix=matrix, alpha=False)
        image = Image.frombytes("RGB", (pix.width, pix.height), pix.samples)
        pages.append(RenderedPage(index, image))
    doc.close()
    return pages


def build_contact_sheet(pages: list[RenderedPage], columns: int, padding: int) -> Image.Image:
    if not pages:
        raise ValueError("No pages rendered from the PDF.")

    label_height = 24
    thumb_width = max(page.image.width for page in pages)
    thumb_height = max(page.image.height for page in pages)
    rows = (len(pages) + columns - 1) // columns
    width = padding + columns * (thumb_width + padding)
    height = padding + rows * (thumb_height + label_height + padding)

    sheet = Image.new("RGB", (width, height), "white")
    draw = ImageDraw.Draw(sheet)

    for idx, rendered in enumerate(pages):
        row = idx // columns
        col = idx % columns
        x = padding + col * (thumb_width + padding)
        y = padding + row * (thumb_height + label_height + padding)
        page = rendered.image
        offset_x = x + (thumb_width - page.width) // 2
        sheet.paste(page, (offset_x, y + label_height))
        draw.rectangle(
            [offset_x, y + label_height, offset_x + page.width - 1, y + label_height + page.height - 1],
            outline=(120, 120, 120),
            width=1,
        )
        draw.text((x, y), f"Page {rendered.page_no}", fill=(0, 0, 0))

    return sheet


def write_report(pdf_path: Path, image_path: Path, report_path: Path, pages: list[RenderedPage], columns: int, zoom: float) -> None:
    report_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# PDF Visual Contact Sheet",
        "",
        "This file is generated by `tools/render_pdf_review_contact_sheet.py`.",
        "",
        "The contact sheet is a visual aid for manual review of the current manuscript PDF. It does not replace page-by-page inspection before final submission.",
        "",
        "## Inputs",
        "",
        f"- PDF: `{pdf_path.relative_to(ROOT)}`",
        f"- Pages: {len(pages)}",
        f"- Render zoom: {zoom}",
        f"- Columns: {columns}",
        "",
        "## Outputs",
        "",
        f"- Contact sheet: `{image_path.relative_to(ROOT)}`",
        f"- Contact sheet size: {file_size(image_path) if image_path.exists() else 'missing'}",
        "",
        "## Review Use",
        "",
        "1. Open the contact sheet to quickly scan for blank pages, oversized figures, table overflow, and figures floating into the conclusion or references.",
        "2. If any page looks suspicious in the contact sheet, open the original PDF and inspect that page at full size.",
        "3. Record the final manual page-by-page result in `paper/CEA_PDF_VISUAL_REVIEW_FORM.md`.",
    ]
    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render a contact sheet for manual PDF visual review.")
    parser.add_argument("--pdf", type=Path, default=DEFAULT_PDF)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--report", type=Path, default=DEFAULT_REPORT)
    parser.add_argument("--zoom", type=float, default=0.35)
    parser.add_argument("--columns", type=int, default=5)
    parser.add_argument("--padding", type=int, default=16)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    pdf_path = args.pdf if args.pdf.is_absolute() else ROOT / args.pdf
    output_path = args.output if args.output.is_absolute() else ROOT / args.output
    report_path = args.report if args.report.is_absolute() else ROOT / args.report

    output_path.parent.mkdir(parents=True, exist_ok=True)
    pages = render_pages(pdf_path, args.zoom)
    sheet = build_contact_sheet(pages, args.columns, args.padding)
    sheet.save(output_path, quality=92)
    write_report(pdf_path, output_path, report_path, pages, args.columns, args.zoom)
    print(f"Wrote {output_path.relative_to(ROOT)}")
    print(f"Wrote {report_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
